### ISSUE TITLE
How difficult is it to get a fairly simple IOS/Android RN app ported to work on RN Windows

### ISSUE THREAD

**Issue by vesper8** [ReactWindows/react-native-windows#1001]
Sorry if this isn't the ideal place to ask. There seems to be almost no discussion of RN for Windows Phones on discuss.reactjs.org which seems to be the biggest community. And I couldn't identify a Slack channel dedicated to React Native either.

Our little startup is currently in the final stages of developing a fairly simple RN app for IOS and Android. It is using Exponent which means that it doesn't depend on any Native modules.. it's strictly javascript along with use of some of the Native modules that Exponent natively supports. We've used NativeBase so we wouldn't have to write different code for both IOS and Android.

I am being asked how feasible it would be to support Windows Phones as well. I don't even have Bootcamp installed on my Mac to begin to test how much work that would entail so I was hoping for some hints of how easy/difficult that is.

In its current state, can you build and deploy apps to the Windows App Store with react-native-windows ?

How much work would it be to port our app over? I'm looking for guesstimates here. I don't expect to do it in a day, not even in a week.. but wondering if in general this library makes things pretty cross-platform or not.

Oh and.. I imagine I absolutely must use Windows to develop this right? There's no Windows Phone emulator for Mac? Anyone have experience trying to do all this in a VM running on OSX?

Anyone else had to port a IOS/Android RN app over to react-native-windows? How did it go? What were the biggest challenges?

Is there a better place where I can ask this type of question and get support if I decide to take this on and run into trouble?

Your time is much appreciated. Thanks!

**Comment by rozele** [comment]
@vesper8 This is absolutely the place to ask.  We also hang out on the reactiflux Discord channel #react-native-platforms and follow activity on the React Native Community Facebook group. It seems there are too many react-native communities :-).

In general, it should be very simple to add react-native-windows support to your app to run on Windows 10 Mobile.  I haven't used Exponent with react-native-windows, but I guess it depends which native modules are used by Exponent.  Same goes for NativeBase.  It looks like NativeBase itself is all JS, but it takes dependencies on:
```
    "react-native-keyboard-aware-scroll-view": "0.2.7",
    "react-native-vector-icons": "~4.0.0",
```
which do not currently have support for react-native-windows.

The best thing to do is just try it out and see what breaks!  Getting started with react-native-windows is easy, just run:
```
npm i --save-dev rnpm-plugin-windows
react-native windows
```

This will install the proper version of `react-native-windows` and generate an `index.windows.js` file.  Edit `index.windows.js` to match the entry point behavior of your iOS and Android apps and you should be good to go (you'll get a red box exception for native modules that may be missing if there are any).

You definitely have to have a Windows environment to build for Windows mobile, here are the specific requirements - https://github.com/ReactWindows/react-native-windows#requirements (the Windows 10 SDK requires Windows 8.1 or higher). Some people have had luck getting things working with [Visual Studio 2017](https://github.com/ReactWindows/react-native-windows/issues/985).

Many have been successful getting started with react-native-windows on a Mac using Parallels or VirtualBox (cc @matthargett).

**Comment by matthargett** [comment]
We actually develop in Windows 7 VMs on Mac, which means we can't use Windows Mobile simulators or run Universal Apps, but we can run our React Native Windows WPF app and its Winium tests :) ReactWindows/f8app is a great reference for navigating the the porting of an RN Android app to Windows. (We're hoping to contribute the WPF variant of f8app soon.)

**Comment by rozele** [comment]
Closing if there are no further comments.
