### ISSUE TITLE
No compatible version found: react-native-windows@undefined

### ISSUE THREAD

**Issue by Juniuz** [ReactWindows/react-native-windows#1005]
Hi, 

In my package.json, `"dependencies": {
    "react": "15.4.2",
    "react-native": "0.41.0"
  }`

When I invoked this command react-native windows --windowsVersion 0.41.0-rc.0, I got the following error below.

![reactnative_windows_error](https://cloud.githubusercontent.com/assets/4703222/22953503/55d2fbf2-f376-11e6-8ab5-94c977e8ab55.JPG)

One week ago, I have used 0.41.0-rc.0 version and it works.  But now I got this error.  Seems like a package version doesn't exist.  I tried  0.42.0-rc.0, but it produces the same error.  What windows version should I use then?

**Comment by coreyRalli** [comment]
Line 49 in node_modules/rnpm-plugin-windows/src/windows.js (in getMatchingVersion()) is returning pkg.version which is undefined. A quick and dirty solution would be to go into the code and pass through the version argument:

`return result.json().then(pkg => version);`

**Comment by rozele** [comment]
Good catch, not sure when the HTTP API stopped responding to the `version` parameter, but it looks like it now responds to http://registry.npmjs.org/react-native-windows/{version}.  To protect against future HTTP API changes, I'm just going to switch to the `npm-registry` package, which is hopefully less likely to break.

**Comment by rozele** [comment]
Please upgrade to rnpm-plugin-windows@0.2.4 to resolve this issue.

**Comment by Juniuz** [comment]
Thanks @rozele  I was now able to install and run react-native on UWP
