### ISSUE TITLE
Using AsyncStorage

### ISSUE THREAD

**Issue by alixeb** [ReactWindows/react-native-windows#1008]
Hello,

Do I need to enable AsyncStorage somewhere via manifest file or other config?
Or does this work out of the box?

I am saving `username` in storage on successful login.
It works fine on Android, but it does not seem to work on Windows. Any suggestions?

#### Saving to storage
` AsyncStorage.setItem('@login:username', username)`

#### Reading from storage
```
AsyncStorage.getItem('@login:username', (err, username) => {
   if (username !== null) {
	this.setState({
	   ...this.state,
	   username
	})
   }
})
```

Help much appreciated

**Comment by rozele** [comment]
It looks like you have a race condition in your app logic.  The call to AsyncStorage.setItem(...) is asynchronous and has a callback parameter.  You have to wait for the callback to be called to guarantee that the item has actually been set before calling getItem.  I imagine it works on Android by coincidence, and that given the right conditions, this bug could also appear on Android.

I reproduced the issue with the following:
```
class Playground extends Component {
  state = {
    value: 0
  }

  componentWillMount() {
    AsyncStorage.clear(() => AsyncStorage.setItem('foo', 42))
  }

  componentDidMount() {

  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native, {this.state.value}!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.windows.js
        </Text>
        <Text style={styles.instructions}>
          Shake or press Shift+F10 for dev menu
        </Text>
      </View>
    );
  }
}
```

However, if I change the logic to:
```
class Playground extends Component {
  state = {
    value: 0
  }

  componentWillMount() {
    AsyncStorage.clear(() => AsyncStorage.setItem('foo', 42), () => AsyncStorage.getItem('foo', (err, value) => this.setState({value})))
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native, {this.state.value}!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.windows.js
        </Text>
        <Text style={styles.instructions}>
          Shake or press Shift+F10 for dev menu
        </Text>
      </View>
    );
  }
}
```

Now calling `getItem` after the `setItem` callback, then the sample behaves as expected.

**Comment by alixeb** [comment]
Hello @rozele,

Thanks for the answer.

At the moment logic in my app is:
1. Call setItem to save username
2. Navigate to next page
3. User leaves app
4. User comes back and username is autofill

So you are saying that I should do step 2 in the callback of `setItem` to guarantee that the value was saved.
I will have a try and let you know.

Cheers

**Comment by rozele** [comment]
Feel free to re-open if that doesn't resolve the issue.

**Comment by alixeb** [comment]
my issue is fixed. thanks for your help
