### ISSUE TITLE
"Could not find react-native-windows@0.41.*" at project setup

### ISSUE THREAD

**Issue by liuxinhu** [ReactWindows/react-native-windows#1026]
Hello everyone,

I got the error `Could not find react-native-windows@0.41.*` when running `react-native windows` after running `npm install --save-dev rnpm-plugin-windows` and manually installing `react-native-windows@0.41.0-rc.1` on Windows 10.

I followed the instructions and they worked fine on a Mac. Anybody have an idea where the problem is?

**Comment by rozele** [comment]
@liuxinhu which version of `rnpm-plugin-windows` do you have installed?

**Comment by liuxinhu** [comment]
The problem is solved. The reason is that I am behind proxy and it is solved by setting proxy.

**Comment by assurancetourix** [comment]
Hello,

I have this issue too. Would it be possible to know exactly how to set the proxy. It's already done on npm with the following commands:
npm config set proxy http://<username>:<password>@<proxy-server-name>:<port>
npm config set https-proxy http://<username>:<password>@<proxy-server-name>:<port>

Is there stg to be done with the react-native command line tool ?

Thanks.
