### ISSUE TITLE
ClipboardModule unit tests crash test execution process

### ISSUE THREAD

**Issue by rozele** [ReactWindows/react-native-windows#262]
When you "run all" the clipboard module unit tests will result in the app crashing.  Please ping @rozele if you cannot repro or need a crash dump.

The issue seems to have to do with access to the dispatcher thread.

**Comment by ebragge** [comment]
@rozele What is your test environment?

I am not able to repro on Surface Pro 3 with Windows 10 10240 (Local machine / Mobile Emulator).

**Comment by rozele** [comment]
I think this crashes if the user has something on their clipboard.
