### ISSUE TITLE
Add ReactSliderManager

### ISSUE THREAD

**Issue by rozele** [ReactWindows/react-native-windows#373]
See: https://msdn.microsoft.com/library/windows/apps/windows.ui.xaml.controls.slider.aspx

**Comment by souhe** [comment]
Hi, I would like to help you guys with react-native-windows. 
So I've started with this task but I have one question. Should it be possible to change for example slider color or other slider specific styles?

**Comment by rozele** [comment]
@souhe Thanks for taking this on!  In the ideal world, the slider behavior would be as close to the slider behavior for iOS and Android as UWP will allow.  So, in that case, at least the props here: http://facebook.github.io/react-native/docs/slider.html.  Of course, it's fine to add extra props that aren't supported on iOS and Android if it's something that UWP easily accommodates.
