### ISSUE TITLE
react-native-cli hooks for UWP

### ISSUE THREAD

**Issue by rozele** [ReactWindows/react-native-windows#4]
Investigate what react-native-cli does for other projects and replicate for UWP.

**Comment by rozele** [comment]
This issue is now more narrowly targeted at implementing a runWindows command for the CLI.

**Comment by rozele** [comment]
Some other things to keep in mind here.  Certain tools, like VS Code, will need hooks to ensure that we launch the app in "debug in Chrome" mode so that it connects to the debugger, rather than runs JavaScript locally.

Also, we'll need a couple additional CLI flags to differentiate between launching on the desktop, launching on an attached device, or deploying to an emulator.

**Comment by grabbou** [comment]
Hey, 

Amazing work so far! Just wanted to say I'm ready to help on adding some missing modules like AppState etc. - might be a good moment to refresh my C# & Windows episode.

Back to the issue... we are working on getting `rnpm` merged into react-native and use some of its internals which means the plug-in system should land there eventually. That would make it possible to dynamically define extra commands, like runWindows or whatever else we may came up with in the future.

Here's the link to current way it's working: 
https://github.com/rnpm/rnpm#plugins

cc: @mkonicek

**Comment by mpodwysocki** [comment]
@grabbou

Thanks, much appreciated! We'd appreciate any work, but before you do, ensure that you follow the [Facebook Contribution Guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md) including signing the CLA or you can wait until this project is merged into the main repository.

This project is not intended (at least as of now) as a fork, and is intended to become part of React-Native itself in the relative near future.  So, CLI commands such as `runWindows` will be built in directly into the CLI once you install react-native.
