### ISSUE TITLE
Generate Correct Identity in Package Manifest for Projects

### ISSUE THREAD

**Issue by ricmatsui** [ReactWindows/react-native-windows#445]
This is probably already in progress, but the latest `react-native-windows` version `0.2.5-rc7` in npm includes a template with a hardcoded identity that doesn't allow it to be run on Windows 10 Mobile out of the box:
```
  <Identity
    Name="00000000-0000-0000-0000-000000000000"
    Publisher="CN=publisher"
    Version="1.0.0.0" />

  <mp:PhoneIdentity PhoneProductId="00000000-0000-0000-0000-000000000000" PhonePublisherId="00000000-0000-0000-0000-000000000000"/>
```
Specifically, `PhoneProductId` must be some value other than `00000000-0000-0000-0000-000000000000` otherwise the following error is thrown during deployment:
```
Error		DEP0001 : Unexpected Error: Package could not be registered. (Exception from HRESULT: 0x80073CF6)
```
The iOS and Android generators use a default package name, e.g. `com.<%= name %>`, and they do not have GUIDs for identifying apps.

- [x] - The generator should create valid or random GUIDs when creating a new project, but not change it for upgrades.
- [ ] - It may also want to accept the identities as parameters or explain to include existing identities if this is for an existing app in the store.

**Comment by rozele** [comment]
Thanks @ricmatsui.  We'll have more updates to this generator this week.

**Comment by rozele** [comment]
Closing this out, user will have to configure their own identities.
