### ISSUE TITLE
Followed instructions, got errors.

### ISSUE THREAD

**Issue by hubert-associates** [ReactWindows/react-native-windows#465]
Followed all instructions, got following. Who can tell me where to start troubleshooting or how to clean-all and start over.

C:\rht\reactuwp>rnpm windows
C:\Users\myuser\AppData\Roaming\npm\node_modules\rnpm\bin\cli:11
updateNotifier({ pkg }).notify();
                     ^
SyntaxError: Unexpected token }
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by rozele** [comment]
can you run rnpm --version and confirm that the output matches:

```
c:\src>rnpm --version
1.8.0
```

**Comment by rozele** [comment]
And could you point us to the documentation you're referring to?

**Comment by hubert-associates** [comment]
thx sec.

**Comment by rozele** [comment]
Can you paste node --version?

**Comment by hubert-associates** [comment]
C:\rht\reactuwp>node --version
v0.12.2
Already too old ? Gosh :-)

**Comment by rozele** [comment]
Please upgrade to node v4 or later...
https://github.com/facebook/react-native/blob/master/react-native-cli/package.json#L8

**Comment by hubert-associates** [comment]
Ok, hmm .... only place that  dependency checks still missing I guess. THANKS for the quick troubleshoot. I'll go back to step 1.

**Comment by rozele** [comment]
Yeah, very strange that it even lets you run RNPM, because RNPM package.json does have the "engine" setting.

**Comment by grabbou** [comment]
Yeah, we should restrict the version to 4 and above since we use ES6 I believe

**Comment by Kureev** [comment]
Yeah, the point of using 4.1+ was in ES6 features it provides. Also, it's a current [LTS version](https://github.com/nodejs/LTS).
