### ISSUE TITLE
Dimensions.get('window') isn't updated on window size changed.

### ISSUE THREAD

**Issue by quincycs** [ReactWindows/react-native-windows#466]
Dimensions.get('window') isn't updated on window size changed.  Is this intended?  I would desire that after/during a layout, this property gets updated so that we can create responsive UI applications just as much as native windows 10 applications can with XAML.

There's a great library which would work if Dimensions.get('window') would be updated.
https://github.com/alpacaaa/react-native-media-queries

**Comment by rozele** [comment]
Thanks for filing @quincycs.  I'll take a look.

**Comment by quincycs** [comment]
thank yoU!  :sob:  so happy
https://twitter.com/quincymitch/status/742731770722955266
