### ISSUE TITLE
Unable to download JS bundle

### ISSUE THREAD

**Issue by abhivijay96** [ReactWindows/react-native-windows#478]
I followed the steps described in https://www.microsoft.com/developerblog/real-life-code/2016/05/27/Creating-Universal-Windows-Apps-with-React-Native.html  to create a new react native uwp project from scratch. I get the following message when I run the app from visual studio .Please help
,I am running this in x64 and local machine 
here is a screenshot of the error.
![react](https://cloud.githubusercontent.com/assets/16561772/16088693/f40a07c6-3345-11e6-850d-323a8c332c72.png)

**Comment by awyl** [comment]
I had the same issue few days ago.  Try goto command line to the project folder.  Then
`react-native start`
This should start the packager.

**Comment by abhivijay96** [comment]
Thank you, it worked, but now it says "requiring unknown module
fbjs/lib/invariant" in the same way, in a red box. Someone please help

**Comment by abhivijay96** [comment]
Thank you, it worked, but now it says "requiring unknown module fbjs/lib/invariant" in the same way, in a red box. Someone please help.

![react](https://cloud.githubusercontent.com/assets/16561772/16093577/087b9684-335a-11e6-88cb-1277a9921c5f.png)

**Comment by rozele** [comment]
Can you check your node_modules folder and make sure node_modules\fbjs\lib\invariant.js exists?

**Comment by abhivijay96** [comment]
Yes,it does exist,is there anyway that i can get rid of this issue?

**Comment by abhivijay96** [comment]
I changed the code in index.windows.js to 
<code> 
import React from 'react';
import { AppRegistry, Text } from 'react-native-windows'; 
const App = () => { return ( <Text>Hello World!</Text> ); }
// App registration and rendering
//console.log(AppRegistry);
AppRegistry.registerComponent('MyApp', () => App);
</code>

Now i am getting the following error : 

 "Unable to get property 'registerComponent' of undefined or null reference" 
[JS Error]"Module AppRegistry is not a registered callable module." 

Someone please help.

**Comment by abhivijay96** [comment]
I re installed all the node modules and it started working thanks for the help.

**Comment by mowi22** [comment]
I'm still getting this error on my windows 10 mobile device even after running "react -native start". App builds and deploys successfully but still I get Red Screen. Any help?

**Comment by abhivijay96** [comment]
Can you please tell what the error says?

**Comment by mowi22** [comment]
"Unable to download JS bundle"

![Uploading wp_ss_20160622_0001.png…]()

**Comment by abhivijay96** [comment]
Can you please try refreshing it a few times.

**Comment by abhivijay96** [comment]
Try this, go to
react-native-windows/blob/master/ReactWindows/ReactNative/DevSupport/DevInternalSettings.cs
in your node modules directory and change " debug_http_host " in the string
constants to local IP address (ip4) of your PC

Eg : something like http://192.168.99.1:port

Where port is where your react native server is listening.
Please try this

**Comment by rozele** [comment]
@mowi22 There is a known issue where the packager server may crash during a build.  Can you check the cmd window where you are running `react-native start` and see if the server is still online?  If it's not, simply restart it with `react-native start` and hit the "Reload JavaScript" button.

**Comment by chukcha-wtf** [comment]
Maybe a similar issue - can't access the bundled file `index.windows.bundle` in `DebugBundle` mode.

![screenshot 4](https://cloud.githubusercontent.com/assets/1046073/16285212/a88cafa4-38dd-11e6-9a22-2fa0e11da032.png)

File seems to be referenced correctly in `MainPage.cs`

```

#if BUNDLE
        public override string JavaScriptBundleFile
        {
            get
            {
                return "ms-appx:///ReactAssets/index.windows.bundle";
            }
        }
#endif
```

and bundle is properly generated. Also ReactAssets folder is included into the project

![screenshot 5](https://cloud.githubusercontent.com/assets/1046073/16285168/64b83780-38dd-11e6-8a43-c6878ce688dc.png)

**Comment by mowi22** [comment]
@rozele @abhivijay96 neither solution worked for me. Here's a screenshot of my environment when I crash. I am on VMWARE (not sure if that has anything to do with it).  This is in the output of VS15 Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.ni.dll. 
![screen shot 2016-06-23 at 4 26 36 am](https://cloud.githubusercontent.com/assets/2376639/16298376/c2b180fe-38fa-11e6-917d-2c04b184b997.png)

**Comment by abhivijay96** [comment]
Please try changing the local ip address in the constant to the local ip
address of the VM.

**Comment by mowi22** [comment]
@abhivijay96 yes thats the IP I used. It didn't work

**Comment by mowi22** [comment]
@abhivijay96 Yes, thats the Ip I used. It didn't work. I tried on port 8081

**Comment by abhivijay96** [comment]
Can you please restart the server after you did the changes in that file?

**Comment by mowi22** [comment]
@abhivijay96 Yes, I've started and restarted the server as @rozele suggested, before and after switching from "debug_http_host" to "my VM's IP.

**Comment by abhivijay96** [comment]
What does the red screen say in the phone?

**Comment by mowi22** [comment]
@abhivijay96 the screen on the phone hasn't changed from what I've posted above. I get that each time I deploy after launch.

**Comment by abhivijay96** [comment]
Please switch off mobile data in the phone and give it a try.

**Comment by mowi22** [comment]
@abhivijay96 Im getting the same. I've gone back through, started and restarted the server and switching to the IP with the data off,still the same error.

**Comment by abhivijay96** [comment]
Can you please try to connect to that address and port from a browser
outside VM .

**Comment by mowi22** [comment]
@abhivijay96 Ok, I'm getting Cannot GET / in the browser outside the VM when I hit that IP and port.(lost as to what that means)

**Comment by abhivijay96** [comment]
So, the address is right, the problem occurs when the phone tries to
connect to the development server , do you have to declare any permissions
to use Internet in Windows phone ? Please check that

**Comment by mowi22** [comment]
@abhivijay96 no, I got my windows 10 phone right out of the box and started working on this. :) I don't have anything restricting its use. I've been able to do just about everything else with the device. The Device portal is working just fine and I'm am able to browse. Not sure whats causing the mix up here.

**Comment by rozele** [comment]
@chukcha-wtf can you check your build output folder and make sure that index.windows.bundle has been copied properly?

**Comment by rozele** [comment]
@mowi22 you said you're getting "Cannot GET /" in the browser outside the VM.  Did you try to hit this endpoint from the device itself?  You may need to open up your Windows Firewall settings to make sure port 8080 is reachable from other devices / machines.

**Comment by mowi22** [comment]
@rozele Ok, I tried with my iphone and got the same "cannot get /" on my mac (outside the VM), android browser and iphone browser. 

However, on the edge browser in the vm and the windows phone I get a 404 error message. 

Every time I hit that endpoint with any device it gets logged back with the IP of the React  package manager prompt, with "404 13". Which I gathered meant that its at least hitting that port. 

I wasn't absolutely sure so I rant a port scanner and its indeed it its open on the 8081 port of my react packager server.

**Comment by abhivijay96** [comment]
https://msdn.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations

Please follow this link.

**Comment by mowi22** [comment]
Compatibility changes haven't gotten me anywhere. Any other suggestions on this? I'm ordering another windows device to rule that out. Currently using (Alcartel Windows 10 Device). I've switched my environment to see if that was the problem, but I'm getting the same result. Deploys correctly to windows simulator. I'm hoping to test on an actual device. Ill report back then.

**Comment by sasivarnan** [comment]
I am also facing the same issue. 

I connected a Windows 10 mobile via USB and I had turned of WiFi and Mobile data.

![image](https://cloud.githubusercontent.com/assets/5305600/16900991/b1ff7934-4c53-11e6-8c62-3c706dc96745.png)

Tried changing the `debug_http_host` to every IP that `ipconfig` command shown. Still issue persists. :disappointed: 

Any idea?

**Comment by andrewwebber** [comment]
After changing "project\node_modules\react-native-windows\ReactWindows\ReactNative\DevSupport\DevInternalSettings.cs" this worked for me. 

Now im trying to find out how to start the "dev menu" on a physical device as shake does not work.

```c#
public string DebugServerHost
        {
            get
            {
                return "172.20.15.142:8081";
                //return GetSetting(DebugServerHostKey, default(string));
            }
            set
            {
                SetSetting(DebugServerHostKey, value);
            }
        }
```

**Comment by rozele** [comment]
@andrewwebber shake should be working on physical devices:
https://github.com/ReactWindows/react-native-windows/blob/master/ReactWindows/ReactNative/DevSupport/DevSupportManager.cs#L455

The dev menu is only available on debug builds.

**Comment by andrewwebber** [comment]
@rozele with the greatest respect you would laugh if you knew how much I've been shaking this Lumia 640XLDS

Still much love for the project though...

**Comment by rozele** [comment]
I definitely believe you, just sounds like a bug with the shake detector.  A while ago, we were having problems with the shake detection on some devices so we switched to a custom shake detector:
https://github.com/ReactWindows/react-native-windows/blob/master/ReactWindows/ReactNative/DevSupport/DevSupportManager.cs#L455

Any chance you could through in some debugging statements to see what (if any) readings you are getting off the accelerometer?  It may be a good time to look into switching back to the UWP built-in shake detector (Windows.Devices.Sensors.Accelerometer.Shaken event).

**Comment by rozele** [comment]
Also, I am able to get the Shaken event to fire on my SurfaceBook for desktop apps!  Very strange that it's not working on the Lumia 640.

**Comment by andrewwebber** [comment]
@rozele i will investigate... as a work around i am just changing the dev settings and enabling hot reloading.

**Comment by rozele** [comment]
@andrewwebber: I'm also trying to create a Dev Settings page so you can customize the localhost address from within the app (similar to how its done for iOS and Android).  This, of course, will not help you if you can't get the shake menu working.

**Comment by andrewwebber** [comment]
@rozele For me it would not be a show stopper as some of the settings could be set host side. Sometimes its kinda annoying (iOS, Android) to try to enter remote ip addresses etc on the phone, so me settings this value in the editor at the moment is not a big show stopper. 

The only issue I am having is modules that some npm modules fail to run on windows like "uuid" as some modules don't exist (Again I am probably doing something stupid or missing something). But I will probably create a seperate issue once i have confirmed this.

```js
var rb = require('crypto').randomBytes;
module.exports = function() {
  return rb(16);
};
```

**Comment by rozele** [comment]
@andrewwebber what version of npm are you running?  People have had trouble with NPM modules not being installed when they were running NPM 2.x

**Comment by andrewwebber** [comment]
@rozele NPM 3.10.3 NODE v6.4.0

**Comment by ndbroadbent** [comment]
I'm also getting this when I try to start the emulator from Visual Studio. It works fine when I run `react-native run-windows`, but that's running the desktop app.

<img width="258" alt="emulator-not-working" src="https://cloud.githubusercontent.com/assets/139536/26053231/424f7b34-3992-11e7-9f66-a07a1a0c1be6.PNG">

**Comment by Hirurgo** [comment]
In UWP by default you can't connect to localhost ip address for security reasons, but windows have a list with apps approved to connect to localhost

Check this https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/loopback

P.S. In our project we had problems with loading JS bundle, **solved this** be by clearing loopback list and add our "package family name" to it again.

**Comment by AliAttariBhai** [comment]
![Screenshot_20200324-231903](https://user-images.githubusercontent.com/49687696/77462820-793bdb80-6e26-11ea-9d0b-501ca1c27379.png)
please solution this

**Comment by ahmadkhudeish** [comment]
I had the same issue when I was running the react native packager while connected to my **work VPN** once I disconnected my work VPN connection the packager was able to pick up the correct IP interface for my app.
