### ISSUE TITLE
 Create [react-native-windows] tag on StackOverflow

### ISSUE THREAD

**Issue by chukcha-wtf** [ReactWindows/react-native-windows#485]
According to `Readme.md` the best way to get some help when working with RN Windows is to post a question on StackOverflow with tag `[react-native-windows]`. I've just tried this and failed. There is no such tag currently present and my reputation (< 1500) isn't allowing me to add this tag to the list.
So it'll be good if someone with higher reputation will create it so others will be able to use it and move this project further by sharing Q/A's.

**Comment by rozele** [comment]
We're going to try and follow reactiflux a bit more closely (the react-native-platforms channel).  Probably no need for a StackOverflow tag.
