### ISSUE TITLE
Eliminate ThemedReactContext

### ISSUE THREAD

**Issue by rozele** [ReactWindows/react-native-windows#489]
I don't think this is needed, but we should further investigate.

**Comment by pre10der89** [comment]
It appears that the intention of the ThemedReactContext is to provide a way to add "view" related context extensions to the ReactContext that is passed into most ViewManagers and their collaborators... However, there does not appear to be any code that utilizes this extension point...  Replacing all instances of ThemedReactContext with ReactContext and removing the instantiation of the ThemedReactContext does not appear to have any effect on running Playground...

**Comment by rozele** [comment]
We'll leave this as won't fix.  ThemedReactContext is a useful way of limiting access from modules to the ReactContext.
