### ISSUE TITLE
Crash in RefCountImageCache's Dispose due to race condition

### ISSUE THREAD

**Issue by rigdern** [ReactWindows/react-native-windows#521]
`RefCountImageCache.Dispose` crashes [here](https://github.com/ReactWindows/react-native-windows/blob/cc5e930b37b02ed8b6f4766297fde2588ea5b964/ReactWindows/ReactNative/Modules/Image/RefCountImageCache.cs#L101) when it is run before `_subscription` has been set. The problem is that `Dispose` assumes that `_subscription` has been set but `_subscription` is not set synchronously in the constructor.

**Comment by rozele** [comment]
thanks @rigdern, the image stuff still needs a lot of work (we need a disk cache for prefetch).  I'll take a look at this though.
