### ISSUE TITLE
Developing on Mac

### ISSUE THREAD

**Issue by ClemMakesApps** [ReactWindows/react-native-windows#528]
I noticed that Windows 10 SDK is only supported on Windows. Is it possible to develop for react-native-windows on the mac platform (besides using a VM)? Is mac support on the roadmap?

**Comment by mpodwysocki** [comment]
@ClemMakesApps right now, we'd like to but building the app requires the Windows 10 SDK which is Windows only.  You can certainly create the scaffolding via `react-cli windows` but you cannot run it on the Mac.
