### ISSUE TITLE
Warnings And Errors of Installation

### ISSUE THREAD

**Issue by myhlivecom** [ReactWindows/react-native-windows#550]
I followed these README.md steps on my Windows 10 PC.
> git clone https://github.com/ReactWindows/react-native-windows.git
> cd react-native-windows
> npm install
> git submodule init
> git submodule update

However, I got warning messages after `npm install`:
> npm WARN react-native-windows@0.31.0-rc.0 requires a peer of react-native@0.31.0-rc.0 but none was installed.
> npm WARN react-native-windows@0.31.0-rc.0 requires a peer of react@~15.2.1 but none was installed.

And I got error messages after `git submodule update`:
> Cloning into 'D:/git/react-native-windows/Examples'...
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> fatal: clone of 'git@github.com:ReactWindows/react-native-windows' into submodule path 'D:/git/react-native-windows/Examples' failed
 
Please help me to solve these warnings and errors.

**Comment by myhlivecom** [comment]
The "peer" dependency problem is solved by manually `npm install` them:
> npm install react-native@0.31.0-rc.0 react@~15.2.1
Peer dependencies are not installed automatically by npm v3...

The publickey problem is solved after I import a publickey to my GitHub account. See:
[https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/](url)

**Comment by myhlivecom** [comment]
There may need a update to README.md for this issue.

**Comment by rozele** [comment]
@myhlivecom: I resolved the node submodule issue, we needed to switch the submodule URL from SSH to HTTPS (https://github.com/ReactWindows/react-native-windows/commit/5e3571ad2d943c652d9cfadcab27971a2d7b12dc).  I'll also update the README.  Thanks!

**Comment by rozele** [comment]
Actually, just decided to make react and react-native devDependencies (as well as peerDependencies), so, just `npm install` will do.

**Comment by myhlivecom** [comment]
Thanks.
