### ISSUE TITLE
No support for "secureTextEntry"

### ISSUE THREAD

**Issue by lznt** [ReactWindows/react-native-windows#574]
Seems to have no support for this, apparently UWP uses PasswordBox: 
https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.controls.passwordbox.aspx

instead of extending their TextBox to have this feature. Anyone already started with this?

**Comment by rozele** [comment]
No one has started this effort yet.

**Comment by mpodwysocki** [comment]
@lznt I'm currently looking into it now

**Comment by mpodwysocki** [comment]
Closed by #580

**Comment by lznt** [comment]
Seems that, when re-rendering the PasswordBox it loses its value given in TextInputs value prop. For example on rotation, if layout changes and PB has to be rerendered. Didn't find anything coherent on .cs side on PasswordBoxManager on a fast glimpse. Any ideas?
