### ISSUE TITLE
Failed to restore the NuGet Packages

### ISSUE THREAD

**Issue by Mayesters** [ReactWindows/react-native-windows#581]
Hi,

I installed react-native-windows according to your guide, but whenever I run the command react-native run-windows it tells me:

Failed to restore the NuGet Packages

Why does that happen? I am running Windows 8.1 and tried non-administrator and administrator permissions.

**Comment by rozele** [comment]
Can you run:
```
.\node_modules\react-native-windows\local-cli\runWindows\.nuget\nuget.exe restore .\<yourapp>\ReactNative.sln
```
From your project root and paste the output. (replace <yourapp> with the folder containing the solution file.

**Comment by Mayesters** [comment]
`node_modules\react-native-windows\local-cli\runWindows\.nuget\nuget.exe restore windo
ws\mTable.sln

MSBuild auto-detection: using msbuild version '4.0' from 'C:\Windows\Microsoft.N
ET\Framework\v4.0.30319'.
C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI
.Xaml.Common.targets(6,18): error MSB4086: Es wurde versucht, einen numerischen
 Vergleich für "$(TargetPlatformMinVersion)" auszuführen, der nicht zu einer Za
hl, sondern zu 10.0.10240.0 ausgewertet wird in der '$(TargetPlatformIdentifier
)' == 'UAP' And '$(TargetPlatformMinVersion)' != '' And '$(TargetPlatformMinVer
sion)' > '10.0.10587.0'-Bedingung. [F:\Eigene Dateien\Eigene Dokumente\Arbeitsp
latz\Programmierung\Apps\mTable\windows\mTable\mTable.csproj]
C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI
.Xaml.Common.targets(6,18): error MSB4086: Es wurde versucht, einen numerischen
 Vergleich für "$(TargetPlatformMinVersion)" auszuführen, der nicht zu einer Za
hl, sondern zu 10.0.10240.0 ausgewertet wird in der '$(TargetPlatformIdentifier
)' == 'UAP' And '$(TargetPlatformMinVersion)' != '' And '$(TargetPlatformMinVer
sion)' > '10.0.10587.0'-Bedingung. [F:\Eigene Dateien\Eigene Dokumente\Arbeitsp
latz\Programmierung\Apps\mTable\node_modules\react-native-windows\ReactWindows\
ReactNative\ReactNative.csproj]`

The German error message (I'm sorry for that, my system lang is German) can be translated to

`It was tried to do a numeric comparison for $(TargetPlatformMinVersion) which didn't result in a number, but in 10.0.10240.0 in the '$(TargetPlatformIdentifier
)' == 'UAP' And '$(TargetPlatformMinVersion)' != '' And '$(TargetPlatformMinVer
sion)' > '10.0.10587.0'- condition`

**Comment by Mayesters** [comment]
After quick research on the error number, I found this StackExchange Thread: http://stackoverflow.com/questions/38181160/error-running-msbuild

The suggested fix to run
`call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"`

Doesn't create an error when running 

```
node_modules\react-native-windows\local-cli\runWindows\.nuget\nuget.exe restore windo
ws\mTable.sln
```

again!

**Comment by Mayesters** [comment]
#582

**Comment by rozele** [comment]
@Mayesters What version of Windows 10 SDK do you have installed?

**Comment by Mayesters** [comment]
I tried Build 10586, which Visual Studio 2015 didn't accept, thus installing 14393. Is is possible that Windows 8.1 is not suitable for Windows UWP development?

**Comment by rozele** [comment]
I haven't tried Windows 8.1, but in theory nothing should be blocking UWP development (it meets the requirements for the Windows 10 SDK).  I also haven't upgraded yet to the 14393 SDK.  I'm still using 10586.

**Comment by matthargett** [comment]
is it possible to have different AppVeyor builds with different SDKs installed?

**Comment by rozele** [comment]
Which SDKs are you referring to?  Having a build for each version of the Windows 10 SDK? Or having a build for 7/8/10?

**Comment by matthargett** [comment]
Having a build for each version of the Windows 10 SDK. It seems like that and slightly older npm installs are the main issues that keep coming up -- despite the updates to the README. Let me know if it's even possible with the AppVeyor config and I can poke around.

**Comment by rozele** [comment]
This seems like a configuration issue with Visual Studio.  Not sure why Visual Studio 2015 would not accept the 10586 build as you stated above.  Closing out this issue, please re-open with new details and a stable repro if this is still a problem.
