### ISSUE TITLE
Release build for deploy

### ISSUE THREAD

**Issue by KalKhera** [ReactWindows/react-native-windows#591]
Are there any detailed instructions on how create a release build with the javascript bundle and resources  include in the app?
Quite new to UWP and would appreciate any help here,

**Comment by rozele** [comment]
Good question @KalKhera.  The docs for this are kind of hidden...
https://github.com/ReactWindows/react-native-windows/blob/master/docs/RunningOnDeviceWindows.md#using-offline-bundle

Basically, assuming you've initialized your project with `rnpm-plugin-windows`, you just generate the bundle as described in that doc and build the project using the `ReleaseBundle` configuration.  Please note, the `Release` builds use the .NET Native compiler, and can take a few minutes.  

For more information about packaging up your app for the Windows Store, see:
https://msdn.microsoft.com/en-us/windows/uwp/packaging/packaging-uwp-apps

**Comment by KalKhera** [comment]
Thanks  for quick response, good work !!
