### ISSUE TITLE
Ensure everything works with Node LTS

### ISSUE THREAD

**Issue by rozele** [ReactWindows/react-native-windows#608]
A few people have noticed that `npm install` does not work for Node LTS, we should figure out what the issue is here.

**Comment by rozele** [comment]
Everything works fine with Node.js LTS (4.5.0), but requires NPM 3.x to install properly.

**Comment by divbit** [comment]
@rozele I think, perhaps, that the npm version you get through facebook's tutorial linked on the react-native-windows readme is not currently 3.x, (on a fresh install of windows this past week I think I got 2.8 something..) which may be causing the problem, maybe adding
```
 npm install -g npm
```
to the readme would help?

**Comment by rozele** [comment]
Thanks @divbit, I think this is mostly covered in @matthargett's PR that gives instructions for Chocolatey packages https://github.com/ReactWindows/react-native-windows/pull/630

**Comment by rozele** [comment]
Also, we had added a line in the main README to signal that npm should be 3.x https://github.com/ReactWindows/react-native-windows/commit/9873f0d0429f7acffe3a666daf0516c3151d66d1

**Comment by rozele** [comment]
There seems to be a problem with haste module resolution on Node LTS.  Simple repro:
* Install Node 4.5 (LTS)
* Run UIExplorer

An exception will occur and the red box will report the PasswordBoxWindows module could not be resolved.

**Comment by divbit** [comment]
@rozele - ah cool thanks - I must have missed that readme line because I retried the tutorial end of last week (in response to a ycombinator thread) and just got around last night to finishing it :)

**Comment by nuthinking** [comment]
How do you install npm 3.x? is that io.js? Thanks.

**Comment by rozele** [comment]
Node LTS is now 6.9.5, so the problem just seems to have gone away :-)
