### ISSUE TITLE
Implement project bridge for CSSLayout

### ISSUE THREAD

**Issue by mpodwysocki** [ReactWindows/react-native-windows#643]
Since the C# bindings have been deprecated, we should use the [C++ CSSLayout](https://github.com/facebook/css-layout/tree/master/CSSLayout) and create a Visual Studio project around it to expose it to WinRT.

**Comment by rozele** [comment]
Updating title, we're now integrating Yoga.

**Comment by rozele** [comment]
This is now complete.
