### ISSUE TITLE
Error during build.... Could not find ReactNative.dll

### ISSUE THREAD

**Issue by kcfgl** [ReactWindows/react-native-windows#648]
I decided to buy a dedicated Windows 10 Pro system instead of using VM on Mac.  So I'm setting everything up.  First off, I had problems installing the plugin following the getting started guide, but doing this worked just fine.
`npm install --save-dev rnpm-plugin-windows@0.1.* `

All the files seem to have generated correctly.  However, when I went to build the project for the first time I got this error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	...\node_modules\react-native-windows\ReactWindows\ReactNative\bin\ARM\Debug\ReactNative.dll' could not be found
```
Everything on this computer should be nice and fresh and I've installed basically all the VS tools and SDKs I need.  Not sure what I might be missing. 

Thanks again @rozele for supporting the devs trying to bring RN to Win, its going to be awesome.

**Comment by rozele** [comment]
@kcfgl which guide are you referring to and which version of react-native are you using?

**Comment by kcfgl** [comment]
Sorry @rozele it was my error. I had a silly space deep in my path.

BUT.  When I run react-native run-windows I get this error:
```

c:\Development\Arriver\node_modules\react-native\node_modules\babel-core\lib\transformation\file\options\option-manager.js:172
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "transform-flow-strip-types" specified in "base" at 0, attempted to resolve relative to "c:\\Development\\Arriver\\node_modules\\react-native-windows\\local-cli"
    at c:\Development\Arriver\node_modules\react-native\node_modules\babel-core\lib\transformation\file\options\option-manager.js:172:17
    at Array.map (native)
    at Function.normalisePlugins (c:\Development\Arriver\node_modules\react-native\node_modules\babel-core\lib\transformation\file\options\option-manager.js:150:20)
    at OptionManager.mergeOptions (c:\Development\Arriver\node_modules\react-native\node_modules\babel-core\lib\transformation\file\options\option-manager.js:224:36)
    at OptionManager.init (c:\Development\Arriver\node_modules\react-native\node_modules\babel-core\lib\transformation\file\options\option-manager.js:338:12)
    at compile (c:\Development\Arriver\node_modules\react-native\node_modules\babel-register\lib\node.js:102:45)
    at loader (c:\Development\Arriver\node_modules\react-native\node_modules\babel-register\lib\node.js:146:14)
    at Object.require.extensions.(anonymous function) [as .js] (c:\Development\Arriver\node_modules\react-native\node_modules\babel-register\lib\node.js:156:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

Running react-native@0.32 

Thanks!

**Comment by rozele** [comment]
@kcfgl It sounds like an issue with installing `rnpm-plugin-windows@0.1.*` You should be using `rnpm-plugin-windows@0.2.*` and using the `react-native-cli` instead of `rnpm` with the latest version of `react-native`.

**Comment by kcfgl** [comment]
@rozele Ah, ok. So new plugin installed. I'll init a new app, drop the existing project in there, run the plugin again and see what happens.  I'm sure its just me missing a critical step since I'm basically cloning an existing, working RN app from Mac to Win.  Thanks again for the extremely fast responses.

**Comment by kcfgl** [comment]
Ugh @rozele  I'm just feeling so dumb right now. I'm simply following the basic set up of a brand new app. Not even using my existing one right now.  And now this error right at the end....

```
c:\Development\Arriver>react-native windows
Installing react-native-windows@0.32.*...
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
react-native-windows@0.32.* successfully installed.

Unknown plugin "transform-flow-strip-types" specified in "base" at 0, attempted to resolve relative to "c:\\Development\\Arriver\\node_modules\\react-native-windows\\local-cli"
```

**Comment by phongcao** [comment]
@kcfgl I used to encounter a similar issue and it got solved after I had used Chocolatey to re-install nodejs, python2 and react-native-cli. [Here](https://facebook.github.io/react-native/docs/getting-started.html) is the detailed instruction.

**Comment by kcfgl** [comment]
@phongcao Thanks for the suggestion, but that did not work.  Same error even after following all the instructions.  @rozele Not sure if you've seen this particular issue before and have any thoughts.

**Comment by kcfgl** [comment]
Scratch that guys, we are now built and running with a new app. I'll move onto the real app now. @phongcao thank you so much for your suggestion. 

@rozele Thank you as always for bringing RN to windows.
