### ISSUE TITLE
ARM Builds Failing

### ISSUE THREAD

**Issue by rozele** [ReactWindows/react-native-windows#649]

**Comment by matthargett** [comment]
1>  pch.cpp
1>c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\dbgprop.h(1387): error C2061: syntax error: identifier 'DebugPropertyInfo'
1>c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\dbgprop.h(1405): error C2061: syntax error: identifier 'DebugPropertyInfo'
1>c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\dbgprop.h(1412): error C2061: syntax error: identifier 'DebugPropertyInfo'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\um\activdbg.h(9409): error C2061: syntax error: identifier 'DebugStackFrameDescriptor'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\um\activdbg.h(9416): error C2061: syntax error: identifier 'DebugStackFrameDescriptor'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\um\activdbg.h(9422): error C2061: syntax error: identifier 'DebugStackFrameDescriptor64'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\um\activdbg.h(9429): error C2061: syntax error: identifier 'DebugStackFrameDescriptor64'

**Comment by rozele** [comment]
@matthargett I can't reproduce this :frowning:
