### ISSUE TITLE
Unable to download JS Bundle - Actual ARM Device

### ISSUE THREAD

**Issue by kcfgl** [ReactWindows/react-native-windows#650]
I can connect to the dev server just fine running on the local.  Very excited about that.  I can even build and deploy to an ARM device (cheap BLU phone for testing, but should work.  Running latest updates to Win 10 as of today).  But I've been working for a couple hours trying to get access to the JS Bundle.  It just wont connect.

I've attempted the fixes mentioned in other threads about setting the DebugServerHostKey.  That doesn't work.  I attempted to simply run react-native run-windows --device, thinking that would have a tighter link.  This starts the packager, but it attempts to install an x86 debug appx.  Which errors out on my device. 

I can't access the Dev Menu either, as shaking the device causes exceptions.

Any other ways I could attempt to get a connection to the server?  At this point, all I want to do is have the satisfaction and confidence to know I can build this app on an actual device.  Thanks for any suggestions.

**Comment by andrewwebber** [comment]
I can only mention what worked for me.

1. react-native start (accept all Windows firewall networks if prompted)
2. Connect your device via USB as well as to the same wireless network as your dev machine (make sure its reachable)
3. Change [DevServerHelper.DeviceLocalHost to your-wlan-ip-address:8081 (excluding http://)](https://github.com/ReactWindows/react-native-windows/blob/master/ReactWindows/ReactNative/DevSupport/DevServerHelper.cs#L20) 
4. F5

**Comment by kcfgl** [comment]
@andrewwebber That worked! You'd think I won the lottery based on my reaction when I saw it.  Thanks for sharing your steps, I appreciate it.

@rozele Shaking the device now works as expected.

**Comment by andrewwebber** [comment]
@kcfgl I know the feeling, I was the same. Just failing to get code push to work on Windows 10, then I'll be really happy

**Comment by kcfgl** [comment]
Good luck! I'm was struggling there on the iOS side for a bit, so I commented all that out before getting to the Win side. I'll tackle that down the road.  Thanks again for your help.

**Comment by kcfgl** [comment]
@andrewwebber Off topic, but you've been an awesome resource so I thought I'd ask.  Have you used custom fonts successfully? Can't seem to work out the right setup.  No worries if you haven't, you've already been a huge help.

**Comment by rozele** [comment]
@andrewwebber any specific issues getting Code Push to work?
