### ISSUE TITLE
Some styles that work for iOS and/or Android have no impact in Win

### ISSUE THREAD

**Issue by kcfgl** [ReactWindows/react-native-windows#651]
I believe I saw something about a guide outlining the differences in some style props between platforms.  That would be extremely helpful.  I'm trying to restyle my app now and running into some issues.

So I cloned the example project and was messing around with the styles to ensure other parts of my existing app were not causing conflict. 

For example: On a TextInput I attempted to set a fontSize: 14, padding: 50. Which on iOS would create a very large input area.  I could also set height in iOS.   

On Win, only the fontSize seems to change.  

Am I missing something or are there just going to be standard styles that won't be available in Win yet?

**Comment by rozele** [comment]
@kcfgl looks like @mattpodwysocki was able to fix a few of the things you requested for text box in https://github.com/ReactWindows/react-native-windows/pull/660, the only thing that does not seem to be supported in UWP is borderRadius on TextBox.

**Comment by kcfgl** [comment]
That's awesome! borderRadius is nice, but usually really subtle, so the newly added styles will cover the vast majority of design needs.  Thanks again!
