### ISSUE TITLE
Release bundle not working

### ISSUE THREAD

**Issue by KalKhera** [ReactWindows/react-native-windows#663]
Exception thrown: 'System.NotImplementedException' in ReactNative.dll
An exception of type 'System.NotImplementedException' occurred in ReactNative.dll but was not handled in user code
Additional information: Enum parsing is not implemented for type 'ReactNative.UIManager.PointerEvents'.

This is after running command s to build bundle in ReactAssets folder.

Anybody get over this issue?

**Comment by rozele** [comment]
@KalKhera which version of react-native-windows? We fixed it in version 0.32, but I can cherry-pick it for older versions.

**Comment by KalKhera** [comment]
Upgraded to 0.32 and works fine.
