### ISSUE TITLE
Tried to build AwesomeProject

### ISSUE THREAD

**Issue by malte1989** [ReactWindows/react-native-windows#667]
Update

I chose Debug x64 then this message appears:

Schweregrad Code    Beschreibung    Projekt Datei   Zeile   Unterdrückungszustand
Fehler  CS0006  Metadatendatei "C:\Users...\AwesomeProject\node_modules\react-native-windows\ReactWindows\ReactNative\bin\x64\Debug\ReactNative.dll" wurde nicht gefunden. AwesomeProject  C:\Users...\AwesomeProject\windows\AwesomeProject\CSC  1   Aktiv

So indeed there is no dll in the x64 folder... only in x86 folder. But then I get other errors, see below.

//Update

Tried to build AwesomeProject for Microsoft UWP, but it fails with the following Errors in Microsoft Visual Studio (Building prio for Android via cmd is all fine in emulator and physical device)

Commands I did before in CMD:
cd AwesomeProject
npm install --save-dev rnpm-plugin-windows
react-native windows
react-native start

The following files are "missing". But if I look into the folders the files are all availeable...
Any hint?

Schweregrad Code    Beschreibung    Projekt Datei   Zeile   Unterdrückungszustand
Fehler      Die Ladungsdatei "C:\Users...\AwesomeProject\node_modules\react-native-windows\ReactWindows\ReactNative\bin\x86\Debug\ReactNative\Bridge\JavaScriptModuleBase.Generated.tt" ist nicht vorhanden.   AwesomeProject  

Schweregrad Code    Beschreibung    Projekt Datei   Zeile   Unterdrückungszustand
Fehler      Die Ladungsdatei "C:\Users...\AwesomeProject\node_modules\react-native-windows\ReactWindows\ReactNative\bin\x86\Debug\ReactNative\ReactNative.xr.xml" ist nicht vorhanden. AwesomeProject          

Schweregrad Code    Beschreibung    Projekt Datei   Zeile   Unterdrückungszustand
Fehler      Die Ladungsdatei "C:\Users...\AwesomeProject\node_modules\react-native-windows\ReactWindows\ReactNative\bin\x86\Debug\ReactNative\Tracing\LoggingActivityBuilderExtensions.tt" ist nicht vorhanden.    AwesomeProject

Schweregrad Code    Beschreibung    Projekt Datei   Zeile   Unterdrückungszustand
Warnung     Für die WINMD-Datei "C:\Users...\AwesomeProject\node_modules\react-native-windows\ReactWindows\ReactNative\bin\x86\Debug\ChakraBridge.winmd" wurde keine Implementierungsdatei bereitgestellt. Legen Sie die "Implementation"-Metadaten für das WINMD-Verweiselement in der Projektdatei fest, um Registrierungsinformationen im App-Manifest zu generieren. AwesomeProject

**Comment by rozele** [comment]
Which version of react-native-windows do you have installed?
```
npm ls react-native-windows
```

**Comment by malte1989** [comment]
-- react-native-windows@0.32.0

**Comment by malte1989** [comment]
package.json
  "dependencies": {
    "react": "15.3.1",
    "react-native": "0.32.0",
    "react-native-windows": "^0.32.0"
  },
  "devDependencies": {
    "rnpm-plugin-windows": "^0.2.0"
  }

So its the same version as react native. Maybe its the old "plugin". Should I remove it? And whats the cmd command?

**Comment by rozele** [comment]
Its suspicious that its trying to find the ChakraBridge project.  I don't think that shipped with v0.32.  Can you paste the contents of node_modules\react-native-windows\ReactWindows\ReactNative\ReactNative.csproj?

**Comment by rozele** [comment]
Curious if you're having a similar issue as what was described in https://www.facebook.com/groups/react.native.community/permalink/822460491222864/.  Do you have any non-ASCII characters in the project path?

**Comment by rozele** [comment]
Also, if you're seeing "ChakraBridge.winmd", that sounds like you're getting some files from our master branch (or from react-native-windows@0.33.0-rc.0).  Any chance you used `npm link` or otherwise changes the contents of the node_modules folder?

**Comment by malte1989** [comment]
npm install -g react-native-cli

was missing. Then the following commands for AwesomeProject Example worked:

npm install --save-dev rnpm-plugin-windows
react-native windows

I am trying if the other projects will work too. I think the global "CLI" was missing.

**Comment by malte1989** [comment]
Btw. I tried to create a new initial Windows App directly in Visual Studio and it worked smoothly.

**Comment by malte1989** [comment]
Over CMD with the following commands I also get error.

npm install --save-dev rnpm-plugin-windows
react-native windows
react-native run-windows

Build failed with message Error: Must have a minimum Windows SDK version 10.0.10586.0 installed. Check your build configuration.

SDK I have installed: 10.0.10586.212

**Comment by malte1989** [comment]
` <TargetPlatformVersion>10.0.10586.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.10240.0</TargetPlatformMinVersion>
    <MinimumVisualStudioVersion>14</MinimumVisualStudioVersion>`

**Comment by nuthinking** [comment]
I keep getting issues too: https://github.com/ReactWindows/react-native-windows/issues/763

Initially because the white spaces in the user name (hence parent folder). Now something else.

**Comment by rozele** [comment]
I'm going to close out this issue, please re-open if you're still having issues getting started with react-native-windows
