### ISSUE TITLE
No scrollbar on listview

### ISSUE THREAD

**Issue by KalKhera** [ReactWindows/react-native-windows#678]
Is this a uwp issue?

Thanks in advance.

**Comment by rozele** [comment]
@KalKhera Are you setting the "showsVerticalScrollIndicator" or "showsHorizontalScrollIndicator" prop?  The defaults for each of these props is false.

**Comment by KalKhera** [comment]
You are correct, works like a treat. 
We will check documentation more carefully in future,
Thanks.
