### ISSUE TITLE
Implement Linking

### ISSUE THREAD

**Issue by rigdern** [ReactWindows/react-native-windows#687]
http://facebook.github.io/react-native/releases/0.33/docs/linking.html#linking

On iOS, this is implemented by [RCTLinkingManager](https://github.com/facebook/react-native/blob/d6fe78fc2538e25a49ce1ec02da743bac6ee5459/Libraries/LinkingIOS/RCTLinkingManager.m).

On Android, this is implemented by [IntentModule](https://github.com/facebook/react-native/blob/3d1b79cd156e8055eab54cefa84a3532572be82c/ReactAndroid/src/main/java/com/facebook/react/modules/intent/IntentModule.java).

**Comment by rozele** [comment]
This should cover it...
* https://github.com/ReactWindows/react-native-windows/blob/master/ReactWindows/ReactNative/Modules/Launch/LauncherModule.cs
* https://github.com/ReactWindows/react-native-windows/blob/master/Libraries/Linking/Linking.windows.js

Just missing https://github.com/ReactWindows/react-native-windows/issues/301.

**Comment by rigdern** [comment]
@rozele What about the [`url` event](https://github.com/ReactWindows/react-native-windows/blob/89c5ff01f40d1bc55f9e26649e56e5545e558f81/Libraries/Linking/Linking.windows.js#L119-L139)? Does it make sense to implement that on Windows?

**Comment by rozele** [comment]
We don't support that, can you elaborate a bit on the expected behavior?
