### ISSUE TITLE
More complete mouse support

### ISSUE THREAD

**Issue by rigdern** [ReactWindows/react-native-windows#688]
Currently, it looks like mouse events just get mapped into RN's [Gesture Responder System](https://facebook.github.io/react-native/docs/gesture-responder-system.html). We need a solution which can support additional scenarios:
  - Events for the mouse pointer hovering over an element, leaving an element, etc.
  - Ability to distinguish between mouse and touch events. For example, you might want an element to respond when the mouse pointer hovers over it but not when a person's finger hovers over/touches it. Similarly, you might want an element to slide when a user drags it with their finger but not when they drag it with their mouse pointer.

While solving this problem, we should also think about styluses.

There is some prior work in this area:
  - React Native has the [Gesture Responder System](https://facebook.github.io/react-native/docs/gesture-responder-system.html) for dealing with touch input.
  - Web browsers have separate touch and mouse events.
  - Web and XAML have pointer events which enable developers to handle all kinds of input devices.

**Comment by rozele** [comment]
I think adding hover events via the PointerEntered and PointerExited is simple.  Differentiating between the touch and click controller is a bit more difficult.

**Comment by rozele** [comment]
Some additional thoughts on PointerEntered and PointerExited events:
* We should decide if we want to support a separate event for each pointer type (e.g., onMouseEntered, onPenEntered) or if we just want to follow the Windows model of having a single pointer event with a pointer type.
* Should the PointerEntered and PointerExited be always available on all views (i.e., handlers being a standard prop of views), or should they be included as Mixins?

**Comment by rozele** [comment]
Here's my proposal:
* Do not follow the Web browser model of separating events for touch and mouse. Instead, follow a model similar to UWP itself which has a pointer type in the event data.  Users can build layers on top of this if they chose to separate the events, e.g.:
```
class Button extends React.Component {
    _onClick() {
        this.props.onClick && this.props.onClick();
     }

    _onTouch() {
        this.props.onTouch && this.props.onTouch();
    }
 
    _onPress(e: Event) {
        if (e.pointerType == 'mouse') {
           this._onClick(e);
        } else if (e.pointerType == 'touch') {
           this._onTouch(e);
       }
     }

     render() {
        return (
           <TouchableWithoutFeedback onPress={this._onPress.bind(this)}>
               {this.props.children}
           </TouchableWithoutFeedback>
        );
     }
}
```
* Have two events, `onPointerEnter` and `onPointerExit` with the same event field for `pointerType`.
* Ensure the `pointerType` event field is propagated through for the PanResponder.

I think this will maximize compatibility with existing components, while at the same time allowing users to customize only when they see it as necessary.

Thoughts?

**Comment by rigdern** [comment]
> Should the PointerEntered and PointerExited be always available on all views (i.e., handlers being a standard prop of views), or should they be included as Mixins?

By "mixin" are you referring to a design like React's [PureRenderMixin](https://facebook.github.io/react/docs/pure-render-mixin.html) which leverages React's `mixins` feature of `createClass`? If so, I don't think we should follow this pattern. The React community is [moving away from mixins](https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html) for a variety of reasons.

I think we should follow the design established by the Gesture Responder System which includes a number of props directly on View (e.g. [onResponderGrant](https://facebook.github.io/react-native/docs/view.html#onrespondergrant)).

---------------------------------------

Here are some thoughts regarding your above proposal:
  - Firing `onPress` for all inputs on high level components like `TouchableWithoutFeedback` sounds reasonable to me.
  - The `onPointerEnter` and `onPointerExit` events sound good.
  - I'm not familiar enough with `PanResponder` to judge whether it makes sense for inputs other than touch.

We also need to think about the Gesture Responder System. If we want to continue pushing non-touch events through it, we'll probably want to include a `pointerType` prop.

**Comment by rozele** [comment]
@rigdern I'll look at this today.

**Comment by rozele** [comment]
For right-click, do you expect the right-click to obey the `pointerEvents`? My immediate intuition would be yes.

**Comment by rozele** [comment]
Something to investigate, can we support something similar to 3D touch with the Pressure property on the pointer events?

**Comment by rigdern** [comment]
> For right-click, do you expect the right-click to obey the `pointerEvents`?

On the web, the `contextmenu` event obeys `pointerEvents` so I think the equivalent for RN should as well.

> Something to investigate, can we support something similar to 3D touch with the Pressure property on the pointer events?

This is not important for my current use case but it's definitely a good thing to consider while working on expanding the input handling of RN.

-----

Here are some general thoughts I have on the API design.

From my observations, RN is designed with a couple of layers of input events. While working on this, I think it's important to keep this in mind.

The lowest layer of events is represented by the Gesture Responder System. This layer is a little verbose/tedious to use but it gives consumers full control over what they want to do with the input events.

Then there's a higher layer of events such as `TouchableWithoutFeedback`'s `onPress` event. This layer gives consumers a convenient and concise way to handle common input scenarios. If they want to do something unusual, they can drop down to the Gesture Responder System to get that control.

Here are design choices that have caused me the most pain in input APIs on the web:
  - Multiple types of input trigger an event (e.g. `onClick` can be triggered by mouse, touch, screen readers) but the event object doesn't indicate the input type. The problem is if the developer wants to do one thing for mouse and another for touch, they are stuck. Options for fixing this:
    1. Include the input type in the event object.
    1. At a lower event layer, offer different events for each input type.
  - A single input triggers multiple events that are at the same layer (i.e. the developer may be simultaneously signed up for more than one of the events). The problem is developers may need to pass information between these events (e.g. to avoid doing an action multiple times) and there's no clean way to do that. They'll have to start worrying about the order the events fire in and they'll have to consider cases where one event fires but the other doesn't.

**Comment by rozele** [comment]
I think we may be directly on target with the approach taken is #773.  All events, whether touch, pen (eraser, regular, or with barrel/alt button), and mouse (left, right, middle click) dispatch through `topTouchStart` (poorly named :-1:), `topTouchMove`, etc. I.e., the basic gesture responder system.  The problem with this, as you say, is that because of the way TouchableWithoutFeedback is designed, all `topTouchEnd` events, whether right click, eraser, etc. will trigger the `onPress`, but it will allow us to build alternative components to Touchable*.

**Comment by rozele** [comment]
@rigdern I've made some progress on the onMouseOver and onMouseOut events.  Basically, we need to create an event plugin for React.js, similar to the [EnterLeaveEventPlugin](https://github.com/facebook/react/blob/master/src/renderers/dom/client/eventPlugins/EnterLeaveEventPlugin.js) and register it in the [ReactNativeDefaultInjection](https://github.com/facebook/react/blob/master/src/renderers/native/ReactNativeDefaultInjection.js#L65).  For good measure, I also added my `ReactNativeEnterLeaveEventPlugin` to the [ReactNativeEventPluginOrder](https://github.com/facebook/react/blob/master/src/renderers/native/ReactNativeEventPluginOrder.js).  The `ReactNativeEnterLeaveEventPlugin` that I created was very dumb.  It didn't have the "only on mouseLeave" feature that ReactDOM has (DOM native mouse events include the "relatedTarget" property, which tells you which element the pointer has exited to, so you can "extract" both the enter and exit event from a single DOM event).

I also needed to fork View.js (as View.windows.js) to include new View props for `onMouseOver` and `onMouseOut`, which kind of sucks, but maybe we can upstream that at some point.

I still need to investigate how to achieve the following:
1) Is it possible to achieve the "only on mouseLeave" behavior?
2) Is there a way we can build out the event plugin and not need an upstream PR to React.js (i.e., inject the EventPlugin)? Currently, it looks like no from [Twitter response](https://twitter.com/sebmarkbage/status/789657338349129728).
3) How will the bubbled/captured events work? Is there anything in particular we need to do to enable this?
4) What kinds of properties are expected on the `nativeEvent`? Do we need `pageX`, `pageY`, `locationX`, `locationY`, etc., or is just the target enough?

**Comment by rigdern** [comment]
It sounds like you've made a lot of progress. Thanks for working on this!

I have some questions:
- What is the "only on mouseLeave" behavior?
- You've been talking about `onMouseOver` and `onMouseOut` events. Have you considered implementing `onMouseEnter` and `onMouseLeave` events? In my experience on web, `enter/leave` are a lot more commonly used than `over/out`. The difference is `enter/leave` only fire when the mouse enters/leaves the element you have attached the listener to. `over/out` fire when the mouse enters/leaves the element you have attached the listener to or any of its descendants. Here are some relevant docs for the web APIs:
  - [mouseenter](https://developer.mozilla.org/en-US/docs/Web/Events/mouseenter)
  - [mouseleave](https://developer.mozilla.org/en-US/docs/Web/Events/mouseleave)

Here's input for some of your questions:

> What kinds of properties are expected on the nativeEvent? Do we need pageX, pageY, locationX, locationY, etc., or is just the target enough?

On web, I mostly use the `stopPropagation()` method on `onMouseEnter` and `onMouseLeave` events (note I'm referring to `enter/leave` and not `over/out` here).

> What are the expected behaviors when pointerEvents of the view or a parent are set to none or box-none?

We should probably be consistent with how browsers handle this.

**Comment by rozele** [comment]
Thanks @rigdern, this is really great feedback, I wasn't aware of the differences between mouseOver and mouseOut.  I already posted #820, which is basically a mouseenter/mouseleave implementation (so I'll change the names of the events), but eventually we'll want a single event plugin that handles all four types of events (over | out | enter | leave).

The "only on mouse leave" behavior was in reference to the way these events are implemented in ReactDOM.  Basically, as an optimization, the synthetic events that are generated for React.js via the plugins for ReactDOM only trigger the creation of synthetic events when for leave events (given the assumption that when a mouse leave event occurs, it must have "entered" another view (or exited the window), which they can extract from the DOM event itself.  I was hoping we could do something similar for React Native.

**Comment by rozele** [comment]
@rigdern I've updated the PR #820 so we now support `onMouseEnter`, `onMouseLeave`, `onMouseOver` and `onMouseOut` where `enter` and `leave` have direct event semantics only, and `over` and `out` have bubbling semantics (with the option to also use `onMouseOverCapture` and `onMouseOutCapture`).

**Comment by rozele** [comment]
I'm going to close this out for now.  We now have nativeEvent details for right-click and other click types, as well as onMouseOver, onMouseOut, onMouseEnter, and onMouseExit events for hover behavior.  We should be able to build a lot of tools on top of this.
