### ISSUE TITLE
Playground has redbox error in all targets, documentation is wrong

### ISSUE THREAD

**Issue by matthargett** [ReactWindows/react-native-windows#692]
Using ReleaseBundle and DebugBundle targets to get Playground running don't work.

The documentation isn't right either -- there is no local-cli/cli.js file, for instance.

I figured out to use the react-native bundler command at the end of the RunningOnDevice docs, doing something like:
$ npm install
[...]
$ react-native bundle --platform windows --entry-file ReactWindows/Playground/index.windows.js --bundle-output ReactWindows/Playground/ReactAssets/index.windows.bundle --assets-dest ReactWindows/Playground/ReactAssets/ 
[....]
bundle: Writing bundle output to: ReactWindows/Playground/ReactAssets/index.windows.bundle
bundle: Done writing bundle output

I then rebuild the ReleaseBundle, which eliminates the "missing ms-appx:ReactAssets/index.windows.bundle", but now I get a red box with
"Requiring unknown module "event-target-shim". If you are sure the module is there, try restarting the packager or running "npm install"."

Of course, I ran npm install from by Bash on Windows. I have node 4.4.7 and npm 2.15.8 installed.

If I add --dev=false to the bundle command and rebuild, I get a further/different redbox message:
"Requiring unknown module "fbjs/lib/invariant".

 I tried upgrading npm to 3.10.7 and re-ran npm install. I then re-ran the bundle command and did a rebuild all in the solution. 

Same result as before: "Requiring unknown module fbjs/lib/invariant"." 

I tried the same steps for DebugBundle configuration, and got the same error messages.

If I can figure out the right incantations, I can send a PR updating the documentation to be correct. But after a few hours, I still don't have it working on my local machine.

**Comment by rozele** [comment]
Good point, we used to have a #if DEBUG statement on the UseDeveloperSupport property of AppReactPage.cs.  I think we removed it because we wanted to use the debug server on Release builds.

**Comment by rozele** [comment]
Might be worth adding it back, I think it's there for the generated code.

**Comment by rozele** [comment]
@matthargett You'll definitely need NPM 3.x, and you may have some cached bundle data that needs to be reset (although I don't think any caching is used with the bundle command).  Very surprised that it's not working, I can't repro with npm 3.10.6.

**Comment by rozele** [comment]
I'll change it so there is no redbox for ReleaseBundle as well as update the documentation.

**Comment by rozele** [comment]
I also just deleted the README in the Playground folder. I didn't realize it was there, and the main README for running the Examples solution is much more useful.

**Comment by matthargett** [comment]
ok, between your commits and rm'ing my node_modules and doing an 'npm install' from scratch with node 4.4.7 and npm 3.10.7, things get much further.

the app starts up, shows the welcome message text, and then crashes in native code due to a JS exception. it does this consistently on startup for me so far.

attached is the thread list and the autos from the stack frame of the crashed thread from the debugger.
<img width="497" alt="playground-crash-autos" src="https://cloud.githubusercontent.com/assets/1550766/18453738/8b726604-78f5-11e6-817c-94e5c6d8a986.png">
<img width="567" alt="playground-crash-threads" src="https://cloud.githubusercontent.com/assets/1550766/18453737/8b710da4-78f5-11e6-8cc9-0fbfb0bb440e.png">


The relevant parts of the inner JavaScriptException:
...
		JavaScriptStackTrace	"__callFunction\r\n    ms-appx:///ReactAssets/index.windows.bundle:7501:1\r\nAnonymous\r\n    function (ms-appx:///ReactAssets/index.windows.bundle:7388:1\r\nguard\r\n    ms-appx:///ReactAssets/index.windows.bundle:7319:1\r\ncallFunctionReturnFlushedQueue\r\n    ms-appx:///ReactAssets/index.windows.bundle:7387:1\r\n"	string
...
...
		Message	"Method 㘠ຘ⽀୶ does not exist on module \0TDeviceEventEmitter\r\n__callFunction\r\n    ms-appx:///ReactAssets/index.windows.bundle:7501:1\r\nAnonymous\r\n    function (ms-appx:///ReactAssets/index.windows.bundle:7388:1\r\nguard\r\n    ms-appx:///ReactAssets/index.windows.bundle:7319:1\r\ncallFunctionReturnFlushedQueue\r\n    ms-appx:///ReactAssets/index.windows.bundle:7387:1\r\n"	string
...

...
		StackTrace	"   at ReactNative.Modules.Core.ExceptionsManagerModule.reportFatalException(String title, JArray details, Int32 exceptionId) in C:\\Users\\Luke Ma\\workspace\\rnw\\ReactWindows\\ReactNative\\Modules\\Core\\ExceptionsManagerModule.cs:line 51\r\n   at _$ILCT$.$ILT$ReflectionDynamicInvoke$.InvokeRetVIII[T0,T1,T2](Object thisPtr, IntPtr methodToCall, ArgSetupState& argSetupState, Boolean targetIsThisCall)\r\n   at System.InvokeUtils.CallDynamicInvokeMethod(Object thisPtr, IntPtr methodToCall, Object thisPtrDynamicInvokeMethod, IntPtr dynamicInvokeHelperMethod, IntPtr dynamicInvokeHelperGenericDictionary, String defaultValueString, Object[] parameters, Boolean invokeMethodHelperIsThisCall, Boolean methodToCallIsThisCall) in f:\\dd\\ndp\\fxcore\\CoreRT\\src\\System.Private.CoreLib\\src\\System\\InvokeUtils.cs:line 463"	string
...

**Comment by rozele** [comment]
What's the deal with "Method 㘠ຘ⽀୶ does not exist on module"?  I haven't seen this before...

**Comment by matthargett** [comment]
That's exactly how it looks in the VS2015 debugger as well -- it's not a mistranslation or copy-paste mangle. I can try to reduce it to a unit test after I update my PCL PR.

**Comment by rozele** [comment]
The strange character issue has been resolved with https://github.com/ReactWindows/react-native-windows/pull/752 and the latest pull request covers generating a MainPage.cs with the right conditionals to turn off developer mode for ReleaseBundle
