### ISSUE TITLE
Add custom appveyor.yml to work around msbuild deficiencies

### ISSUE THREAD

**Issue by matthargett** [ReactWindows/react-native-windows#699]
I have a working AppVeyor build, with more complete build coverage that the default CI, with this configuration:

```
version: 1.0.{build}
image: Visual Studio 2015
build_script:
- cmd: >-
    nuget restore ReactWindows\ReactNative.sln
    set DEVENV="%VS140COMNTOOLS%\..\IDE\devenv"
    %DEVENV% /build "Debug|x64" ReactWindows\ReactNative.sln
    npm install -g npm
    npm version
    npm install -g react-native-cli
    npm install
    mkdir ReactWindows\Playground\ReactAssets
    react-native bundle --platform windows --entry-file ReactWindows/Playground/index.windows.js --bundle-output ReactWindows/Playground/ReactAssets/index.windows.bundle --assets-dest ReactWindows/Playground/ReactAssets/
    %DEVENV% /build "ReleaseBundle|x64" ReactWindows\ReactNative.sln
    %DEVENV% /build "DebugBundle|x64" ReactWindows\ReactNative.sln
    %DEVENV% /build "Debug|x86" ReactWindows\ReactNative.sln
    %DEVENV% /build "Debug|ARM" ReactWindows\ReactNative.sln
    %DEVENV% /build "Release|x86" ReactWindows\ReactNative.sln
    %DEVENV% /build "Release|ARM" ReactWindows\ReactNative.sln        
    %DEVENV% /build "ReleaseBundle|x86" ReactWindows\ReactNative.sln
    %DEVENV% /build "ReleaseBundle|ARM" ReactWindows\ReactNative.sln

```

If it's agreeable, I'll send a PR adding the appveyor.yml. The project-side plumbing will need to be done by an admin, though. The max total build time so far is ~20 minutes, the ReleaseBundle taking most of the time due to the intensive .NET Native compilation.

The next step after the initial PR (and successful builds) would be to allow for VS2013 image, which would be straightforward.

**Comment by rozele** [comment]
Currently, I'm only building one release build because otherwise the build queues become unbearably long.  Unfortunately, you can only have one Appveyor project per open source repo (for free), but ideally we'd have one build queue that ran the gauntlet for commits to master and another build queue that ran a bare minimum of the release builds so we could get rapid feedback on the pull requests.

**Comment by rozele** [comment]
Also, as I mentioned in Discord, we're considering moving to VSTS which has been support for build agents (so we'd actually be able to run tests in CI).

**Comment by matthargett** [comment]
Build queue becomes unbearably long for a <25 minute build? We can ask AppVeyor to turn on parallel builds for the project (for free). We can also only do one ReleaseBundle build (for just x64), since the .NET Native part is where most of the time is spent. That being said, the rate of PRs and merges so far aren't coming in at a rate where the queue would be more than an hour deep AFAICS. As another option, integrating with the Chakra Jenkins instance and registering agents there  is something we're open to since there's multiple responsive vendors we can engage to get support/consulting.

**Comment by matthargett** [comment]
Quick update. If I remove the x32 and ARM ReleaseBundle parts of the build, it's down to 20 minutes.

**Comment by rozele** [comment]
@matthargett I think this work is now complete, closing this out.  Feel free to re-open if there are remaining tasks for appveyor.yml
