### ISSUE TITLE
react-native-drawer - non-drawer content not interactive

### ISSUE THREAD

**Issue by joewood** [ReactWindows/react-native-windows#715]
Using react-native-windows 0.33.1 and RN 0.33,
When using [react-native-drawer](https://github.com/root-two/react-native-drawer) the main content (the child) of the `Drawer` compoennt is not interactive. On iOS and Android the same code works fine. No `onPress` event handlers fire for any elements.  Simple example code below:

```typescript
<Drawer
	ref="navigation"
	open={state.open}
	onOpen={() => {setState({open:true});}
	onClose={() => {setState({open:false};}
	type="displace"
	content={<Settings />}
	tapToClose={true}
	openDrawerOffset={0.2}
	panCloseMask={0.2}
	negotiatePan={true}
	tweenHandler={(ratio: number) => ({
		main: { opacity: Math.max(0.54, 1 - ratio) }
	})}>
	<View style={{width:200,height:200, backgroundColor:"red",margin:50}}>
		<Text onPress={()=>console.log("PRESS")}>Text</Text>
	</View>
</Drawer >
```

**Comment by rozele** [comment]
@joewood I think it's because it's not rendering a valid drawer.  I think the windows implementation for react-native-drawer would need to be added to get this to work.  In the case of Android, I assume it uses DrawerLayout, and for Windows it would likely use SplitView.

**Comment by joewood** [comment]
Hi @rozele, I don't think that is the problem here.  The draw works fine when opened. The issue is interactive event propagation to the child content when the draw is closed.  This is a pure JS solution, and not dependent on any native layout.

**Comment by joewood** [comment]
It may  be worth noting, react-native-drawer-layout works OK (when you use the IOS code, which doesn't delegate to the Android native layout component). I think react-native-drawer is doing something funky with the pan responder. There's definitely a  compatibility issue there somewhere. 

Ideally we would have a native uwp switch component that can be used that looks like the native android one.

**Comment by rozele** [comment]
@joewood I think you're right on with the issue being related to the touch implementation.  I used the Live Visual Tree debugger in Visual Studio, and it seems that there is a full page overlay sitting over the main content that is intercepting all the touch operations.

**Comment by rozele** [comment]
It may be that we're missing a feature to disable touch on a view so those same touches are intercepted instead by the correct view.

**Comment by rozele** [comment]
In fact, that full page overlay has "pointerEvents" == "none", so the pointerEvents implementation could be the issue.

**Comment by rozele** [comment]
Thanks @joewood, this was a great find.  We should have this fixed soon.  Is there a particular version you need this patched on, or can it wait for the next release of react-native-windows?

**Comment by joewood** [comment]
Hi @rozele nothing too urgent. I switched over to the [react-native-drawer-layout](https://github.com/iodine/react-native-drawer-layout) which didn't suffer from the overlay problem. I'm sure this one would have reared itself in other places though. Thanks for looking into it so quickly.
