### ISSUE TITLE
AccessViolationException

### ISSUE THREAD

**Issue by thurber** [ReactWindows/react-native-windows#726]
Hello,

Thanks for your work on this library!

I'm getting an "AccessViolationException" when trying to run my project (currently working fine on iOS and Android) with `react-native-windows` v0.34.0 (same error occurred on v0.33.0). The error seems to be thrown from a TextInput of type password. Below is my code for the particular component, and a screenshot from the error in VisualStudio.

As a disclaimer, I'm not at all familiar with Windows/VisualStudio development. It should also be noted that I am running Windows inside a VirtualBox from a Mac, so if this is truly some kind of memory access issue as the screenshot suggests, it might be caused by my virtual environment.

code:
```javascript
...
<TextInput
  ref='password'
  style={{
    flex: 1,
    height: 40,
  }}
  value={this.props.password}
  secureTextEntry={true}
  editable={!this.props.loading}
  placeholder='password'
  placeholderTextColor={Styles.lightGray}
  underlineColorAndroid='transparent'
  keyboardType='default'
  returnKeyType='go'
  selectTextOnFocus={true}
  autoCorrect={false}
  autoCapitalize='none'
  onChangeText={(p) => {
    this.props.setPassword(p)
  }}
  onSubmitEditing={() => {
    this.refs.password.blur()
    this.props.submit(this.props.username, this.props.password, this.props.rememberMe)
  }}
/>
...
```

screenshot:
![image](https://cloud.githubusercontent.com/assets/5023771/18963164/a00c867c-8628-11e6-8302-37dfe94f39e7.png)

Thanks for any insight!

**Comment by rozele** [comment]
@mpodwysocki any thoughts?
