### ISSUE TITLE
Plans for MapView?

### ISSUE THREAD

**Issue by joewood** [ReactWindows/react-native-windows#737]
`MapView` is an iOS only feature in react-native according to the [docs](http://facebook.github.io/react-native/docs/mapview.html). I was wondering if there was any activity around developing this component, given that it's still marked as TBD on the roadmap. I can see a few options:

* Develop as a standalone component that could be optionally compiled in by the packager
* Add it to the core **react-native-windows** build to emulate the IOS native component
* Submit a PR to [airbnb](https://github.com/airbnb/react-native-maps) for their cross platform component

**Comment by rozele** [comment]
I think contributing to airbnb repo would be the best option, if we can get it accepted.  Second best option would be to create a different standalone component, and only as a last resort bake it into core.

Removing the iOS Map component was actually up for discussion at one point:
https://www.facebook.com/groups/reactnativeoss/permalink/1533524910277471/

**Comment by rozele** [comment]
MapView is being deprecated from react-native (https://github.com/facebook/react-native/pull/10500), can you file an issue against https://github.com/airbnb/react-native-maps repo to add Windows support?
