### ISSUE TITLE
Exception when attempting to run offline bundle with ReleaseBundle build

### ISSUE THREAD

**Issue by kcfgl** [ReactWindows/react-native-windows#743]
Below is the crash dump saved at exception.  The app builds but right at the point where the JS Bundle would be fetched from dev server, it errors out.   I set UseDeveloperSupport to false as well.

I'm still on 0.32 (haven't updated because I've hit issues with other modules).  

Dump Summary
------------
Dump File:	arriver.dmp : C:\Development\Arriver\arriver.dmp
Last Write Time:	10/5/2016 6:53:14 PM
Process Name:	arriver.exe : C:\Data\SharedData\PhoneTools\AppxLayouts\FullGlassLabsLLC.ArriverVS.ReleaseBundle_ARM.kane\arriver.exe
Process Architecture:	ARM
Exception Code:	0x80000004
Exception Information:	A trace trap or other single-instruction mechanism signaled that one instruction has been executed.
Heap Information:	Not Present

System Information
------------------
OS Version:	10.0.14393
CLR Version(s):	

Modules
-------
Module Name	Module Path	Module Version
-----------	-----------	--------------
arriver.exe	C:\Data\SharedData\PhoneTools\AppxLayouts\FullGlassLabsLLC.ArriverVS.ReleaseBundle_ARM.kane\arriver.exe	1.0.0.0
ntdll.dll	C:\windows\SYSTEM32\ntdll.dll	10.0.14393.187
KERNELBASE.dll	C:\windows\System32\KERNELBASE.dll	10.0.14393.187
arriver.dll	C:\Data\SharedData\PhoneTools\AppxLayouts\FullGlassLabsLLC.ArriverVS.ReleaseBundle_ARM.kane\arriver.dll	1.0.0.0
combase.dll	C:\windows\System32\combase.dll	10.0.14393.187
ucrtbase.dll	C:\windows\System32\ucrtbase.dll	10.0.14393.187
RPCRT4.dll	C:\windows\System32\RPCRT4.dll	10.0.14393.187
kernel32legacy.dll	C:\windows\System32\kernel32legacy.dll	10.0.14393.187
bcryptPrimitives.dll	C:\windows\System32\bcryptPrimitives.dll	10.0.14393.187
SharedLibrary.dll	C:\data\Programs\WindowsApps\Microsoft.NET.Native.Framework.1.3_1.3.24201.0_arm__8wekyb3d8bbwe\SharedLibrary.dll	1.4.24201.0
mrt100_app.dll	C:\data\Programs\WindowsApps\Microsoft.NET.Native.Runtime.1.4_1.4.24201.0_arm__8wekyb3d8bbwe\mrt100_app.dll	1.4.24201.0
OleAut32.dll	C:\windows\SYSTEM32\OleAut32.dll	10.0.14393.187
chakra.dll	C:\windows\SYSTEM32\chakra.dll	11.0.14393.187
clrcompression.dll	C:\Data\SharedData\PhoneTools\AppxLayouts\FullGlassLabsLLC.ArriverVS.ReleaseBundle_ARM.kane\clrcompression.dll	1.0.24214.0
wintypes.dll	C:\windows\SYSTEM32\wintypes.dll	10.0.14393.187
VCRUNTIME140_APP.dll	C:\data\Programs\WindowsApps\Microsoft.VCLibs.140.00_14.0.24123.0_arm__8wekyb3d8bbwe\VCRUNTIME140_APP.dll	14.0.24123.0
msvcp_win.dll	C:\windows\SYSTEM32\msvcp_win.dll	10.0.14393.187
msvcrt.dll	C:\windows\SYSTEM32\msvcrt.dll	7.0.14393.187
iertutil.dll	C:\windows\SYSTEM32\iertutil.dll	11.0.14393.187
sechost.dll	C:\windows\System32\sechost.dll	10.0.14393.187
advapi32legacy.dll	C:\windows\SYSTEM32\advapi32legacy.dll	10.0.14393.187
shcore.dll	C:\windows\SYSTEM32\shcore.dll	10.0.14393.187
SspiCli.dll	C:\windows\SYSTEM32\SspiCli.dll	10.0.14393.187
mrt100.dll	C:\windows\SYSTEM32\mrt100.dll	1.0.24120.0
procthreadexthost.dll	C:\windows\SYSTEM32\procthreadexthost.dll	0.0.0.0
kernel.appcore.dll	C:\windows\SYSTEM32\kernel.appcore.dll	10.0.14393.187
ntmarta.dll	C:\windows\SYSTEM32\ntmarta.dll	10.0.14393.187
modernapiexthost.dll	C:\windows\SYSTEM32\modernapiexthost.dll	0.0.0.0
SecRuntime.dll	C:\windows\SYSTEM32\SecRuntime.dll	0.0.0.0
msvcp110_win.dll	C:\windows\SYSTEM32\msvcp110_win.dll	10.0.14393.187
PsmApp.dll	C:\windows\SYSTEM32\PsmApp.dll	10.0.14393.187
WpPortingLibrary.dll	C:\windows\SYSTEM32\WpPortingLibrary.dll	0.0.0.0
twinapi.appcore.dll	C:\windows\SYSTEM32\twinapi.appcore.dll	10.0.14393.187
bcrypt.dll	C:\windows\SYSTEM32\bcrypt.dll	10.0.14393.187
Windows.UI.Xaml.dll	C:\Windows\System32\Windows.UI.Xaml.dll	10.0.14393.187
minuser.dll	C:\windows\SYSTEM32\minuser.dll	0.0.0.0
win32u.dll	C:\windows\System32\win32u.dll	10.0.14393.187
Bcp47Langs.dll	C:\windows\SYSTEM32\Bcp47Langs.dll	10.0.14393.187
CoreMessaging.dll	C:\windows\SYSTEM32\CoreMessaging.dll	10.0.14393.187
GDI32.dll	C:\windows\SYSTEM32\GDI32.dll	10.0.14393.187
gdi32min.dll	C:\windows\SYSTEM32\gdi32min.dll	10.0.14393.187
xamlpalwp.dll	C:\windows\SYSTEM32\xamlpalwp.dll	10.0.10011.16384
AppChromeAPI.dll	C:\windows\SYSTEM32\AppChromeAPI.dll	0.0.0.0
ShellChromeAPI.dll	C:\windows\SYSTEM32\ShellChromeAPI.dll	0.0.0.0
CoreUIComponents.dll	C:\windows\SYSTEM32\CoreUIComponents.dll	0.0.0.0
windows.storage.dll	C:\windows\SYSTEM32\windows.storage.dll	10.0.14393.187
powrprof.dll	C:\windows\SYSTEM32\powrprof.dll	10.0.14393.187
shlwapi.dll	C:\windows\SYSTEM32\shlwapi.dll	10.0.14393.187
profapi.dll	C:\windows\SYSTEM32\profapi.dll	10.0.14393.187
MrmCoreR.dll	C:\windows\SYSTEM32\MrmCoreR.dll	10.0.14393.187
dwrite.dll	C:\windows\SYSTEM32\dwrite.dll	10.0.14393.187
CoreApplicationShim.dll	C:\windows\System32\CoreApplicationShim.dll	0.0.0.0
AppModelProxy.dll	C:\windows\System32\AppModelProxy.dll	0.0.0.0
dxgi.dll	C:\windows\SYSTEM32\dxgi.dll	10.0.14393.187
ActXPrxy.dll	C:\Windows\System32\ActXPrxy.dll	10.0.14393.187
Windows.Phone.Devices.dll	C:\windows\System32\Windows.Phone.Devices.dll	0.0.0.0
EMCLIENT.dll	C:\windows\SYSTEM32\EMCLIENT.dll	10.0.14393.187
AgHostSvcs.dll	C:\windows\SYSTEM32\AgHostSvcs.dll	10.0.14393.187
OnDemandBrokerClient.dll	C:\windows\SYSTEM32\OnDemandBrokerClient.dll	10.0.14393.187
TaskHostCore.dll	C:\windows\SYSTEM32\TaskHostCore.dll	10.0.14393.187
TASKHOSTSVCS.dll	C:\windows\SYSTEM32\TASKHOSTSVCS.dll	10.0.14393.187
WpCoreUtil.DLL	C:\windows\SYSTEM32\WpCoreUtil.DLL	0.0.0.0
storageusage.dll	C:\windows\SYSTEM32\storageusage.dll	10.0.14393.187
Windows.UI.ApplicationTheme.dll	C:\windows\System32\Windows.UI.ApplicationTheme.dll	0.0.0.0
ZTrace.dll	C:\windows\SYSTEM32\ZTrace.dll	0.0.0.0
PHONEINFO.dll	C:\windows\SYSTEM32\PHONEINFO.dll	0.0.0.0
d3d11.dll	C:\windows\SYSTEM32\d3d11.dll	10.0.14393.187
qcdx11um8612.dll	C:\windows\SYSTEM32\qcdx11um8612.dll	9.18.2058.0
MSVCR120.dll	C:\windows\SYSTEM32\MSVCR120.dll	12.0.21005.1
Windows.Devices.Sensors.dll	C:\Windows\System32\Windows.Devices.Sensors.dll	10.0.14393.187
BiWinrt.dll	C:\windows\SYSTEM32\BiWinrt.dll	10.0.14393.187
cfgmgr32.dll	C:\windows\SYSTEM32\cfgmgr32.dll	10.0.14393.187
sensorsnativeapi.dll	C:\windows\SYSTEM32\sensorsnativeapi.dll	10.0.14393.187
SensorsNativeApi.V2.dll	C:\windows\SYSTEM32\SensorsNativeApi.V2.dll	10.0.14393.187
SensorsUtilsV2.dll	C:\windows\SYSTEM32\SensorsUtilsV2.dll	10.0.14393.187
PROPSYS.dll	C:\windows\SYSTEM32\PROPSYS.dll	7.0.14393.187
deviceaccess.dll	C:\windows\system32\deviceaccess.dll	10.0.14393.187
mrmenvironmentext.dll	C:\windows\SYSTEM32\mrmenvironmentext.dll	0.0.0.0
Windows.UI.dll	C:\windows\SYSTEM32\Windows.UI.dll	10.0.14393.187
dcomp.dll	C:\windows\SYSTEM32\dcomp.dll	10.0.14393.187
ShellRuntime.dll	C:\windows\System32\ShellRuntime.dll	0.0.0.0
Windows.Web.Http.dll	C:\Windows\System32\Windows.Web.Http.dll	10.0.14393.187
rometadata.dll	C:\windows\SYSTEM32\rometadata.dll	4.6.1586.0
Windows.Networking.Connectivity.dll	C:\Windows\System32\Windows.Networking.Connectivity.dll	10.0.14393.187
Windows.Networking.HostName.dll	C:\windows\SYSTEM32\Windows.Networking.HostName.dll	10.0.14393.187
WS2_32.dll	C:\windows\SYSTEM32\WS2_32.dll	10.0.14393.187
mswsock.dll	C:\windows\system32\mswsock.dll	10.0.14393.187
DNSAPI.dll	C:\windows\SYSTEM32\DNSAPI.dll	10.0.14393.187
NSI.dll	C:\windows\SYSTEM32\NSI.dll	10.0.14393.187
IPHLPAPI.DLL	C:\windows\SYSTEM32\IPHLPAPI.DLL	10.0.14393.187
dhcpcsvc6.DLL	C:\windows\SYSTEM32\dhcpcsvc6.DLL	10.0.14393.187
dhcpcsvc.DLL	C:\windows\SYSTEM32\dhcpcsvc.DLL	10.0.14393.187
StorageProxy.dll	C:\windows\System32\StorageProxy.dll	0.0.0.0
Windows.Storage.ApplicationData.dll	C:\windows\SYSTEM32\Windows.Storage.ApplicationData.dll	10.0.14393.187
inputhost.dll	C:\windows\SYSTEM32\inputhost.dll	0.0.0.0
XamlDiagnostics.dll	C:\Data\SharedData\PhoneTools\11.0\Debugger\bin\RemoteDebugger\XamlDiagnostics.dll	10.0.14393.33
WindowsXamlDiagnosticsTap.dll	C:\Data\SharedData\PhoneTools\11.0\Debugger\bin\RemoteDebugger\WindowsXamlDiagnosticsTap.dll	14.0.25527.1
windowscodecs.dll	C:\windows\system32\windowscodecs.dll	10.0.14393.187
windows.ui.core.textinput.dll	C:\windows\SYSTEM32\windows.ui.core.textinput.dll	10.0.14393.187
TextInputFramework.dll	C:\windows\SYSTEM32\TextInputFramework.dll	10.0.14393.187
Windows.Graphics.dll	C:\Windows\System32\Windows.Graphics.dll	10.0.14393.187
CRYPTBASE.dll	C:\windows\SYSTEM32\CRYPTBASE.dll	10.0.14393.187
WinRtTracing.dll	C:\Windows\System32\WinRtTracing.dll	10.0.14393.187
threadpoolwinrt.dll	C:\Windows\System32\threadpoolwinrt.dll	10.0.14393.187
urlmon.dll	C:\windows\SYSTEM32\urlmon.dll	11.0.14393.187
XmlLite.dll	C:\windows\SYSTEM32\XmlLite.dll	10.0.14393.187
Windows.Globalization.dll	C:\Windows\System32\Windows.Globalization.dll	10.0.14393.187
RMClient.dll	C:\windows\System32\RMClient.dll	10.0.14393.187
directmanipulation.dll	C:\windows\system32\directmanipulation.dll	10.0.14393.187
AppModelCore.dll	C:\windows\System32\AppModelCore.dll	10.0.10011.16384
ie_shims.dll	C:\windows\SYSTEM32\ie_shims.dll	0.0.0.0

**Comment by rozele** [comment]
@kcfgl can you drop the .dmp file in a public share somewhere so I can try and open it?

**Comment by kcfgl** [comment]
@rozele Here you go:  https://1drv.ms/u/s!ApXgQsHMBsBLiAl19IEF-gwIPtsq

Let me know if it doesn't work or if you need me to try to collect more data

**Comment by rozele** [comment]
@kcfgl can you get a full dump instead of a minidump?  I can't debug the minidump

**Comment by kcfgl** [comment]
@rozele sorry for my stupidity about this, but even with the registry key DumpType set to 2 (full dump) my only options are minidump and minidump with heap when saving the dump file after the exception.

**Comment by kcfgl** [comment]
@rozele in the absence of a full dump (which I'm still working to get you) here are the last few lines in the debug output right as the exception occurred.

```
Exception thrown: 'ReactNative.Chakra.JavaScriptUsageException' in ReactNative.dll
'arriver.exe' (Win32): Loaded 'C:\Windows\system32\AppModelCore.dll'. Skipped loading symbols. Module is native, and native debugging is currently disabled.
'arriver.exe' (Win32): Loaded 'C:\Windows\system32\ie_shims.dll'. Skipped loading symbols. Module is native, and native debugging is currently disabled.
Exception thrown: 'System.NullReferenceException' in ReactNative.dll
An exception of type 'System.NullReferenceException' occurred in ReactNative.dll but was not handled in user code
Additional information: Arg_NullReferenceException
```

**Comment by rozele** [comment]
@kcfgl can you apply the patch in #745 and see if this fixes your issue?

**Comment by kcfgl** [comment]
@rozele patch applied, but sadly the same exception happens. I hesitate to try to update to latest npm given the issues last time. but im now wondering if that might be the only option.

**Comment by kcfgl** [comment]
@rozele in case its somehow relevant, here is the releasebundle configuration. i did not make any edits to what was pre-set.

![arrv_config](https://cloud.githubusercontent.com/assets/19731815/19158823/2f89d55e-8bb8-11e6-81be-0895ec68438b.PNG)

**Comment by kcfgl** [comment]
@rozele minidump with heap should work, right? https://1drv.ms/u/s!ApXgQsHMBsBLiA-Ff8TSaY2CZon9

**Comment by rozele** [comment]
@kcfgl okay, maybe the best thing to go for is a small repro if possible.  Are you able to make this argument null exception occur for a very basic app I could try out?

**Comment by kcfgl** [comment]
@rozele Got a sample app up. Using 0.32 as well.  It is just the basic RN init app.  Works with debug, same exact error as above when trying to use ReleaseBundle

https://github.com/kcfgl/rn-win-test

**Comment by rozele** [comment]
@kcfgl that example is 0.33.  Does this only repro on ARM?  Or can it also repro on x64 on Desktop?

**Comment by kcfgl** [comment]
@rozele youre right about 0.33, i apologize i missed that.  i can probably bump my real project to .33 since the big Chakra changes which caused the app not to work for me aren't until .34.

Yes, i can repro on x64 on Desktop.

**Comment by rozele** [comment]
can you paste MainPage.cs in here?

**Comment by kcfgl** [comment]
sure here is \windows\cleanapp\MainPage.cs

```
using ReactNative;
using ReactNative.Modules.Core;
using ReactNative.Shell;
using System.Collections.Generic;

namespace cleanapp
{
    class MainPage : ReactPage
    {
        public override string MainComponentName
        {
            get
            {
                return "cleanapp";
            }
        }

#if BUNDLE
        public override string JavaScriptBundleFile
        {
            get
            {
                return "ms-appx:///ReactAssets/index.windows.bundle";
            }
        }
#endif

        public override List<IReactPackage> Packages
        {
            get
            {
                return new List<IReactPackage>
                {
                    new MainReactPackage(),
                };
            }
        }

        public override bool UseDeveloperSupport
        {
            get
            {
                return true;
            }
        }
    }

}

```

**Comment by rozele** [comment]
@kcfgl You said you tried setting:
```
        public override bool UseDeveloperSupport
        {
            get
            {
                return true;
            }
        }
```
Can you try replacing with the following?
```
        public override bool UseDeveloperSupport
        {
            get
            {
#if !BUNDLE || DEBUG
                return true;
#else
                return false;
#endif
            }
        }
```

**Comment by kcfgl** [comment]
@rozele just tried it on desktop and it resulted in a different error:
```

An exception of type 'ReactNative.Chakra.JavaScriptUsageException' occurred in System.Private.CoreLib.dll but was not handled in user code
Additional information: Invalid argument.
If there is a handler for this exception, the program may be safely continued.
```

**Comment by rozele** [comment]
As of https://github.com/ReactWindows/react-native-windows/pull/753, the UseDeveloperSupport property should be configured correctly.  Not sure yet what's causing the JavaScriptUsageException and can't repro from either 0.32 or 0.33

**Comment by rozele** [comment]
We're kind of all over the place, was this latest exception on 0.32 or 0.33?  If so, was it in the project that you downgraded to 0.32 in? Did you downgrade all the other dependencies as well?

**Comment by kcfgl** [comment]
OK so I'll keep that code block you sent me and I'll add it to my main project. 

As for the other error... Any chance its a system configuration issue and not a project config issue?

**Comment by kcfgl** [comment]
Sorry, I'll try to get it together. The latest exception occurred on .32, which I downgraded to match my main project. i downgraded react and react-native to match as well.

**Comment by rozele** [comment]
okay. just wanted to be sure.  I have a project that I upgraded to 0.33, and can now downgrade to 0.32 to see if I can repro, but initially wasn't able to repro for the default project on the 0.32 or upgraded 0.33.

**Comment by kcfgl** [comment]
OK, sorry for the confusion. I'm on .32 for both react-native and react-native-windows. 15.3.1 for react. For both this test project and the main project I'm most concerned about.

**Comment by rozele** [comment]
No worries, not your fault at all, I need to come up with a better issue template for reporting things!  I appreciate all your efforts in getting to the bottom of this!

**Comment by kcfgl** [comment]
Believe me, I'm the one who appreciates you helping to solve this, especially since you're not easily able to replicate this one.  Its helping to keep me from pulling my hair out for sure

**Comment by kcfgl** [comment]
@rozele I have to take the app away from the dev machine Wednesday. Worst case I could take my mac with me, do you think its possible to bring my windows JS files over to the Mac, update the DeviceLocalhost to mac IP address and have it load the win files?  I would doubt it, right?

**Comment by rozele** [comment]
In theory, this should work just fine.  There shouldn't be anything Windows specific to the packager, it's all just node-haste recognizing the *.windows.js pattern.

**Comment by kcfgl** [comment]
@rozele Ok, that makes me feel at least a little better that I might have a fallback plan.  I'm sure I'm just not seeing it, but can I pull from the dev server but still shut off the redbox or other alerts?

Basically, can I make it look like its pulling from the offlineBundle when its not?

**Comment by kcfgl** [comment]
@rozele Getting back to this weird exception. Is there anything on the project setup side that I might be missing that you can think of? I was really hoping you would easily reproduce the issue, but since you cant, I'm wondering if there is something simple I'm missing in the ReleaseBundle configuration, etc.....

**Comment by kcfgl** [comment]
@rozele This probably isnt relevant but I can trigger what looks like the same exception by doing a Release build with the packager not running. It tried to access the JS, then errors out.

When I run a Debug build with the packager not running, it tried to get the JS files, can't, then I get the RN Red Screen "Unable to download JS bundle."  Exceptions are showing in the console but they dont crash the app.

Grabbing at straws here ...

**Comment by kcfgl** [comment]
@rozele Sorry to keep hammering you with updates but I'm still trying to make this work before this demo.  

I just set up a completely new app, basic react-native init, and react-native-windows@0.34.1.  Runs fine in debug mode. Crashes with ReleaseBundle.  Same basic exception.  The issue  HAS to be my system config right? I didn't modify a single line of code on this one and it still won't build.

```
An exception of type 'ReactNative.Chakra.JavaScriptUsageException' occurred in System.Private.CoreLib.dll but was not handled in user code

Additional information: Argument is not an object.
```

Does this lead your mind down any other path?  Thanks again Eric.

**Comment by rozele** [comment]
Sounds like this https://github.com/ReactWindows/react-native-windows/issues/719, did you run the react-native bundle command?  It's not run automatically by the build process.

**Comment by kcfgl** [comment]
@rozele Unbelievable oversight on my part and a huge waste of your time. Not sure I'll ever be good enough to contribute, but I'll find a way to give back.  Eric, thank you as always for your support.

**Comment by rozele** [comment]
Finding issues and gaps in the documentation like this is extremely helpful, so you've already given back.  Very much appreciate your resilience in getting to the bottom of this :-).  We'll get #719 fixed ASAP so we don't confuse users in the future!
