### ISSUE TITLE
Native exception when JS calls a native method during initial script run

### ISSUE THREAD

**Issue by rigdern** [ReactWindows/react-native-windows#744]
When JS calls a native method too early during app initialization, I'm seeing an exception on this line because `_bridge` is `null`: https://github.com/ReactWindows/react-native-windows/blob/788061fde25648880a472f1c1f3f7cd1791f535b/ReactWindows/ReactNative/Bridge/ReactInstance.cs#L142

I believe this is the line that is running the JS: https://github.com/ReactWindows/react-native-windows/blob/788061fde25648880a472f1c1f3f7cd1791f535b/ReactWindows/ReactNative/Bridge/ReactInstance.cs#L117

Notice that `_bridge` hasn't been assigned at that point.

I suspect you can repro this bug by calling a native method at the toplevel of `index.window.js`.

**Comment by rozele** [comment]
Sounds like it could be related to #743
