### ISSUE TITLE
Unknown plugin "transform-flow-strip-types" specified in "base"

### ISSUE THREAD

**Issue by nuthinking** [ReactWindows/react-native-windows#763]
Struggling quite a bit to run RN on Windows.

Any idea on how to fix it? I believe I have all the software up-to-date.

Thanks!

![screenshot 2016-10-11 10 14 53](https://cloud.githubusercontent.com/assets/163635/19265393/e4d1506c-8f9c-11e6-9a65-cc20f3df26a9.png)

**Comment by nuthinking** [comment]
Actually I had an old NPM (no idea why). Still have the error after update though.

**Comment by rozele** [comment]
did you re-run npm install after the update?

**Comment by nuthinking** [comment]
yes

**Comment by matthargett** [comment]
Also try doing an rm -rf node_modules . When moving from old npm to new, I always had to do that to shake out remaining issues for some reason.

**Comment by nuthinking** [comment]
yep, after emptied the modules and install again, new projects now seem to run. A couple of warnings but should be fine.
