### ISSUE TITLE
Add right-click (or onContextMenu) event APIs

### ISSUE THREAD

**Issue by rozele** [ReactWindows/react-native-windows#774]
Desktop apps need to overload right-click behavior.  This is related to #688.

**Comment by rigdern** [comment]
Also consider how to handle this scenario for non-mouse inputs (e.g. for keyboard there's a context menu key and for touch there's press and hold)

**Comment by rozele** [comment]
Well, there is a concept of a `FlyoutMenu` in UWP, but I don't think anything specific to trigger context menus.  Keyboard is a whole other class of issues we'll need to create (i.e., I should be able to "tab" through the UI to focus on Controls, simulate `onPress` (potentially) using the return key when focused on a button, open a context menu, etc.  But yeah, let's leave that for another time and keep this issue specific to just having the bare minimum option to recognize a right-click.  Feel free to file an issue on context menus separately.

**Comment by rigdern** [comment]
Okay, I moved the context menu event discussion to #777. As mentioned in #777, I think right-click and context menu are related enough that we should consider the design for both of them before implementing right-click.
