### ISSUE TITLE
Redbox included in release builds

### ISSUE THREAD

**Issue by rigdern** [ReactWindows/react-native-windows#790]
I configured my app to build with the `ReleaseBundle` configuration. When a JS exception occurred, a redbox popped up.

In production, you never want a user to see a redbox so the feature should be disabled in release builds.

**Comment by rozele** [comment]
@rigdern which version of react-native and react-native-windows?

**Comment by rigdern** [comment]
I found the problem. I created my project a while ago before [this commit](https://github.com/ReactWindows/react-native-windows/commit/8aaa0b155975a227f74a25ea3f9044d3ad6c912c) disabled dev features in release builds.
