### ISSUE TITLE
Typo in "on device" instructions?

### ISSUE THREAD

**Issue by rigdern** [ReactWindows/react-native-windows#791]
Is it correct to have the equals sign in `--dev=false`? None of the other arguments use an equals sign.

**Comment by rozele** [comment]
@rigdern index.windows.js is generally the correct "entry" file for the projects generated by our project generator script, we use the "bundle" convention for the output file (after the --bundle-output flag).

The `=` sign may be a typo though.

**Comment by rigdern** [comment]
Oops, I misread the `.js` extension as being associated with the output file.

I updated the issue description to remove the part about the extension.

**Comment by rozele** [comment]
@rigdern I tested it, and it works, but you are correct, `=` is optional for `commander` flags and its not used elsewhere so....
