### ISSUE TITLE
route.component.name is different on device and in debugging

### ISSUE THREAD

**Issue by Petter-W** [ReactWindows/react-native-windows#797]
I use the name of the component in my to decide what should be in my Navigator.NavigationBar. When I'm debugging get the full name of the component (e.g. "mainview" or "intro"). On device I'll only get one letter. I other words; I can't change the LeftButton and RightButton depending on the view.

**Comment by rozele** [comment]
@Petter-W When you refer to the "name" of the component, which specific prop are you referring to?  Can you paste some sample code where you're getting the name of the component?

**Comment by Petter-W** [comment]
@rozele This is how i currently use the NavigationBar. This works just fine when I run it in debug on my machine, but when i run it on my Windows phone,  "route.component.name" returns a single letter.
[navigator.txt](https://github.com/ReactWindows/react-native-windows/files/536259/navigator.txt)

**Comment by Petter-W** [comment]
This is inside <Navigator navigationBar={<Navigator.NavigationBar />} /> btw.

**Comment by Petter-W** [comment]
This is inside `<Navigator navigationBar={<Navigator.NavigationBar />} />` btw.

**Comment by Petter-W** [comment]
It seems to work if I set the `--dev true`  when I generate the bundle.

**Comment by rozele** [comment]
which version of react-native-windows?

**Comment by Petter-W** [comment]
I'm currently at 0.35.0. I could try with a newer version, but I doubt that it will help…

**Comment by rozele** [comment]
could you put together a sample that reproduces the error?

**Comment by rozele** [comment]
@Petter-W if this is still an issue, can you re-open and post a repro?
