### ISSUE TITLE
Run javascript on react-native context.

### ISSUE THREAD

**Issue by ayunawani** [ReactWindows/react-native-windows#821]
Hi,
I want to execute javascript code natively in react-native's context. So how can i do that?

I have tried getting the context of react-native and but on assigning this context on JavaScriptContext.Current  i am getting this error  **"Runtime is active on another thread."**.

Thanks in advance,
Ayush Nawani

**Comment by rozele** [comment]
@ayunawani JavaScript runtimes are single-threaded, so you can't have multiple threads accessing Chakra simultaneously.  I think you have two options:
a) Use ReactContext.RunOnJavaScriptQueueThread(() => { /* do stuff */ });
b) Create your own Chakra runtime instance to run your own JavaScript

Obviously b) only makes sense if you're not needing to use any assets / resources from the bundle you generated.

**Comment by ayunawani** [comment]
Thanks @rozele .
ReactContext.RunOnJavaScriptQueueThread() solved my problem.

**Comment by wasd171** [comment]
@rozele could you provide any highlight on b) though? I have an Electron-based app, where all heavy logic is done in the main process, and renderer process is lightweight for better UX. Is it possible to create something like a WebWorker?
