### ISSUE TITLE
Add to template's gitignore file

### ISSUE THREAD

**Issue by rigdern** [ReactWindows/react-native-windows#832]
These two entries should be added:
- `*.VC.db`
- `*.VC.VC.opendb`

**Comment by rozele** [comment]
Can you submit a PR :-)

**Comment by rigdern** [comment]
Sure. I'm busy at the moment and filing a bug was quicker. When I have some time, I'll do a PR and give you some feedback on your mouse change. Sorry for the delay on that.

**Comment by rozele** [comment]
no worries, thanks @rigdern.  I commited the change for now, it's very simplistic.  We can always revisit for a heavier approach (like EventPlugins) at a later point.  Still would be great if you had a look!

**Comment by GantMan** [comment]
Happy to help do this.   Link me to the spot, and feel free to github assign.

**Comment by rigdern** [comment]
@GantMan Thanks, this is the file: https://github.com/ReactWindows/react-native-windows/blob/e7b90d86de47992bd7a61b7153ca2d2bcf27110c/local-cli/generator-windows/templates/_gitignore.
