### ISSUE TITLE
Use alternative package URL for development?

### ISSUE THREAD

**Issue by joewood** [ReactWindows/react-native-windows#849]
Where is the correct place to override the package URL for the JavaScript code in development? I don't see this documented anywhere - I may be missing it.

**Comment by rozele** [comment]
Typically, here: https://github.com/ReactWindows/react-native-windows/blob/master/local-cli/generator-windows/templates/src/MainPage.cs#L23, just the one that was generated for your project.

**Comment by joewood** [comment]
Isn't that the embedded bundle asset? 
How about the packager URL for developer mode?

**Comment by rozele** [comment]
oh, sorry, misunderstood.  We haven't created a dev settings page for runtime configuration of that yet (https://github.com/ReactWindows/react-native-windows/issues/358).  However, you can manually configure it here: https://github.com/ReactWindows/react-native-windows/blob/master/ReactWindows/ReactNative.Shared/DevSupport/DevServerHelper.cs#L63

**Comment by joewood** [comment]
Actually, I see you can override the JavaScriptMainModuleName in the ReactPage to specify the URL path. At least, that's how Playground does it.

**Comment by rozele** [comment]
oh, okay, sorry, yeah.  It's the JavaScriptMainModuleName (I think this is the same on Android).  E.g., https://github.com/ReactWindows/react-native-windows/blob/be5c02e5fadcf17586fc5737a559bb1189b518ca/UIExplorer/windows/UIExplorerApp/MainPage.cs#L22
