### ISSUE TITLE
Using secureTextEntry on TextInput shifts down input on UWP.

### ISSUE THREAD

**Issue by Xyfi** [ReactWindows/react-native-windows#855]
I've been having trouble with the secureTextEntry. When I use it on my text input it gets shifted down a notch like shown here:

### Not using secureTextEntry

![Without secureTextEntry](http://i.imgur.com/U4xT15e.png)

### Using secureTextEntry

![With secureTextEntry](http://i.imgur.com/7WdV6qx.png)

### Example

Down here is an example written in typescript, that shows the issue.

```javascript
import * as React from "react";
import { View, StyleSheet, TextInput } from "react-native";

export default () => {
    return (
        <View style={styles.containerStyle}>
            <TextInput
                style={styles.inputStyle}
                placeholder={"Enter your password"}
                secureTextEntry
                />
        </View>
    );
};

const styles = StyleSheet.create({
    inputStyle: {
        fontSize: 18,
        lineHeight: 23,
        flex: 1
    } as React.TextStyle,
    containerStyle: {
        height: 40,
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#000"
    } as React.TextStyle,
});
```
I've use the inspector to try and find out where the extra spacing is comming from but I couldn't find any abnormalities.

Is this a bug or am I missing something?

**Comment by rozele** [comment]
Sounds like a bug, yes. Thanks for filing @Xyfi

**Comment by rozele** [comment]
Which version of react-native and react-native-windows?  I'm not able to repro.

**Comment by Xyfi** [comment]
"react-native": "0.35.0",
"react-native-windows": "^0.35.0"

The result images are from a windows app.

**Comment by Xyfi** [comment]
I did some more research and I found out that the container component doesn't wrap around the TextInput properly when secureTextEntry is used. I've created a self contained example:

```
import * as React from "react";
import {
    StyleSheet,
    View,
    Platform,
    TextInput
} from "react-native";

class App extends React.Component<{}, {}> {
    render(): JSX.Element {
        return (
            <View style={styles.container}>
                <View style={styles.inputContainer}>
                    <TextInput />
                </View>
                <View style={styles.inputContainer}>
                    <TextInput secureTextEntry />
                </View>
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: "space-around"
    } as React.ViewStyle,
    inputContainer: {
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#F5FCFF",
        borderWidth: 1,
        borderColor: "black"
    } as React.ViewStyle
});

export default App;
```

**Comment by rozele** [comment]
Thanks @Xyfi

**Comment by rozele** [comment]
@Xyfi, this is an issue with the measurement function for PasswordBox in XAML.

**Comment by rozele** [comment]
@Xyfi I have the fix above, I'll try to patch it into 0.36 and make sure it gets into 0.37

**Comment by Xyfi** [comment]
Thank you!

**Comment by rozele** [comment]
I'm going to leave this open for bookkeeping until we get the PR merged.
