### ISSUE TITLE
onMouseOver and pals

### ISSUE THREAD

**Issue by GantMan** [ReactWindows/react-native-windows#858]
`onMouseOver` and associated mouse hover events don't seem to be working in RNW.

This is a continuation of a our dischordapp communication where I posted this example:
![image](https://cloud.githubusercontent.com/assets/997157/20025561/72a9a500-a2bd-11e6-868d-3336bf846d5e.png)

This was tested with RNW 0.36.1 and 0.37.0-rc.0, where neither event would fire.

**Comment by rozele** [comment]
onMouse[Over|Out|Enter|Exit] is not supported on Touchable* (for reference, see [TouchableWithoutFeedback](https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/TouchableWithoutFeedback.js#L168-L184)).

Easiest thing to do is just add the mouse hover event handlers to the single child element of the Touchable* element.

onMouse[Over|Out|Enter|Exit] was introduced as of 0.37.0-rc.0.
