### ISSUE TITLE
Unable to run react-native run-windows after a git clean

### ISSUE THREAD

**Issue by kwancherie** [ReactWindows/react-native-windows#859]
Hi,

I did the following:

react-native init ProjectName
cd ProjectName
npm install --save-dev rnpm-plugin-windows
react-native windows

react-native run-windows

Works fine.

Then I did
git clean -fxd
npm install
react-native run-windows

And I get the following error:

Building D:/Code/ProjectName/windows/ProjectName.sln
ERROR: The system was unable to find the specified registry key or value.
Found MSBuild v14.0 at C:\Program Files (x86)\MSBuild\14.0\bin
Found MSBuild v12.0 at C:\Program Files (x86)\MSBuild\12.0\bin\amd64\
Found MSBuild v4.0 at C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
Building Solution: D:/Code/ProjectName/windows/ProjectName.sln
Build configuration: Debug
Build platform: x86
Build failed with message Error: Command failed: "C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe" "D:/Code/ProjectName/windows/ProjectName.sln" /clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal /nologo /p:Configuration=Debug /p:Platform=x86
. Check your build configuration.

Should something be not included in the .gitignore file? I didn't touch/change any of the code.
Note: it builds perfectly fine using visual studio.

Thanks

**Comment by rozele** [comment]
I just tried to repro.  Created a new project with:
react-native init myapp
npm i --save-dev rnpm-plugin-windows
react-native windows
git init
git clean -fxd
npm i
react-native run-windows

and was not able to repro.

Can you run (from a Developer Command Prompt for VS2015):
```
msbuild D:\Code\ProjectName\windows\ProjectName.sln
```
and paste what the specific error is?

Potentially, if you already ran git clean, you may first have to run:
```
D:\Code\ProjectName\node_modules\react-native-windows\local-cli\runWindows\.nuget\nuget.exe restore D:\Code\ProjectName\windows\ProjectName.sln
```
(react-native run-windows does this for you)

**Comment by kwancherie** [comment]
Thanks! It looks like I had a .gitignore file that was ignoring *.pfx so the TemporaryKey.pfx was getting removed.

**Comment by rozele** [comment]
Great, closing out then.
