### ISSUE TITLE
ScrollView doesn't work when added to secondary Tabs

### ISSUE THREAD

**Issue by adisoftbn** [ReactWindows/react-native-windows#873]
Hello,

I have a react-native-tab-view control with multiple tabs.
In every tab I have a scroll view with content.

ScrollView responds to Touch and Mouse Scroll only from the first tab. In first tab i have an option which enables a second scroll view and hides the first. Second scroll view works too if belongs to the first tab.

If I use inspector(enable selection from debug menu) and enable VerticalScrollBar showing, the scrolling works when i use the scrollbar drag, but still doesn't repond to mouse scroll or device tuch.

If I switch Tabs, I get the same results, first tab works and the rest not.

It works perfectly from android and ios.

Tested on WinPC/WinMobile Redstone.

I have React Native Windows 0.37.1/React Native 0.37. Didn't worked also on older releases, but I thought there was a bug in my code.

Best regards,
Adrian.

**Comment by rozele** [comment]
Thanks @adisoftbn.  Can you paste the JS from a repro?  Even better if you can set up a small git repo with the repro.

**Comment by adisoftbn** [comment]
Hello :)

Successfully got some free time and made a small demo.
Works perfectly on Android, but on Windows, the scroll works only on the first tab.

[https://github.com/adisoftbn/ReactNativeWinTabViewTest](https://github.com/adisoftbn/ReactNativeWinTabViewTest)

Best regards,
Adrian

**Comment by rozele** [comment]
@adisoftbn thanks for the repro, it looks like this is related to https://github.com/ReactWindows/react-native-windows/issues/563.  We're having an issue with XAML where ScrollViewer does not behave properly when you apply a matrix transform to it.

**Comment by rozele** [comment]
@adisoftbn I published a workaround that I still need to test out a bit before I decide if it is worth merging into master.  However, I believe this will unblock you until I can get the upstream issue with scrolling combined with Matrix3DProjections resolved.  Here it is: https://github.com/rozele/react-native-windows/commit/a316f3db574eca81d448b822b216007c99c5370d

**Comment by adisoftbn** [comment]
Hello @rozele :)

I tried with both stable and RC version of react-native-windows(also react-native and react rc) and if i replace the file BaseViewManager.cs with your chnages, the tabs wont work anymore. If i restore original code, tabs are working, but scroll works only with the first scrollview.

Is there anything else that needs to be done(aditional changes to the rc version of react-native-windows) ?

**Comment by rozele** [comment]
@adisoftbn that's strange. I implemented the workaround from your test project and the tabs were working.  Are you testing the change on your test project or your actual project?

**Comment by adisoftbn** [comment]
I tested on both projects.

For example in the screen it should be on Tab5. Tab5 is selected, but it shows first Tab.

![image](https://cloud.githubusercontent.com/assets/1209902/20321103/e9210134-ab7c-11e6-9783-372e984de138.png)

**Comment by rozele** [comment]
Yeah wow.  Didn't catch that.

**Comment by rozele** [comment]
@adisoftbn can you try out the code in the PR I sent: https://github.com/ReactWindows/react-native-windows/pull/888?  I made a few minor changes that fix the tab-not-switching problem

**Comment by adisoftbn** [comment]
Hey @rozele  :)

It seems to fix the problem. Everything seems to work as expected. I'm still testing it. 

Checked the app for about 10 minutes on a Lumia. Haven't found any issues that might be related to it yet. But I will still test it in the next days, and I will deploy the app to some friends to see if it causes any issues or so :)
