### ISSUE TITLE
react-native-windows depends on nightly builds

### ISSUE THREAD

**Issue by Xyfi** [ReactWindows/react-native-windows#877]
I've been having some issues updating react-native-windows because it depends on nightly/early builds from react-native and react. I think it would be easier for developers if react-native-windows would depend on the latest stable npm packages of react-native. 

Care to share your thoughts on this?

**Comment by rozele** [comment]
@Xyfi I try to keep the master branch always pointed at the latest RC from facebook/react-native.  In fact, I'd prefer to point it at master from facebook/react-native.  If you're looking for a more stable experience, try out one of the release branches.  If there are ever any commits in master that you need cherry-picked onto a release branch, just let me know.
