### ISSUE TITLE
`react-native windows` does not work behind strict firewall

### ISSUE THREAD

**Issue by yaakov-h** [ReactWindows/react-native-windows#879]
When running the steps in the setup guide, `react-native windows` fails when reading data from the NPM registry when direct HTTPS access is unavailable.

As far as I can tell, there is no option to use a proxy server instead.

I have NPM working through a proxy with `npm config set proxy` and `npm config set https-proxy`, and can only set up react-native-windows by tampering with windows.js inside the rnpm-plugin-windows directory.

I've copied the full command-line output [to this gist](https://gist.github.com/yaakov-h/4cc1b7f8ea8a444847c27dcb2e5edfd9) as I was having issues with multi-line markdown formatting.

**Comment by rozele** [comment]
There's actually no real reason to use https here, would changing the script to use http work?

**Comment by yaakov-h** [comment]
Nope, port 80 is also blocked on this network.

**Comment by rozele** [comment]
@yaakov-h if you have suggestions for what to use besides `fetch` for this step: https://github.com/ReactWindows/react-native-windows/blob/master/local-cli/rnpm/windows/src/windows.js#L39, it would be great if you could file a PR.

**Comment by yaakov-h** [comment]
@rozele: You could use `fetch (url, { agent: someHttpAgentObjectThatHasProxyOptionsSet })`, but I don't know node/npm/react well enough to know how to get the proxy options from npm or somewhere else.

**Comment by sasivarnan** [comment]
Facing the same issue here. Any update on this?
Here is an example of using proxy with `node-fetch` https://github.com/bitinn/node-fetch/issues/79#issuecomment-184594701

**Comment by matthargett** [comment]
Sounds like you figured it out -- care to submit a PR?

**Comment by sasivarnan** [comment]
@matthargett I have raised a PR #963. Kindly check it out.

**Comment by matthargett** [comment]
fixed by #963
