### ISSUE TITLE
Not able to checkout 'Chakracore' &  'Examples' folder to local

### ISSUE THREAD

**Issue by cvcnsprakash** [ReactWindows/react-native-windows#908]
Cloning the repository to local, ends up with following error:
Git failed with a fatal error.
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=No error
github.com[1: 192.30.253.112]: errno=No error

And, the folders 'Chakracore' and 'Examples' are empty except for a .git file inside.
Tried downloading as zip file. both the folders are missing there too!
Also, both the folders are greyed in Github.

Is there any issue or am I getting it wrong?!

**Comment by rozele** [comment]
They are submarines, you'll need to run git submodule init and git submodule update.

**Comment by cvcnsprakash** [comment]
Adding   git config --global url."https://".insteadOf git://   did the trick!
Added the same in comment, as it might help someone!
