### ISSUE TITLE
Question: Button component

### ISSUE THREAD

**Issue by alixeb** [ReactWindows/react-native-windows#909]
Hello,

I was wondering if you are supporting `<Button>` or not

There is no information about it on the core parity page.
https://github.com/ReactWindows/react-native-windows/blob/master/docs/CoreParityStatus.md

If you could please update`CoreParityStatus.md`.

Thanks

**Comment by rozele** [comment]
@alixeb Button is not currently supported, but it's easy to add support for, since its simply a wrapper with some default styles around TouchableOpacity (ios) and TouchableNativeFeedback (android).

**Comment by alixeb** [comment]
Thanks for the quick reply.
Looking at your commit: TouchableOpacity is also compatible with windows and it is the wrapper as you have this line:
``const Touchable = Platform.OS === 'android' ? TouchableNativeFeedback : TouchableOpacity;``

**Comment by rozele** [comment]
Thanks for pointing that out, I'll dig a bit more to determine the expected "on press" behavior for native Windows buttons.
