### ISSUE TITLE
How long we will have support react with UWP? 

### ISSUE THREAD

**Issue by alexandrubeu** [ReactWindows/react-native-windows#910]
Hi, 
  We have a xbox one ADK project which has to be migrated to UWP. I was wondering if I can use react-native ? 

I've search into  http://facebook.github.io/react-native/ and I didn't see any tutorial for windows UWP. 

Do you intend to maintain this repository ?

**Comment by matthargett** [comment]
From my side, we have a multi-year commitment to React Native Windows. Even though our focus is on WPF, our goal is to keep as much code Shared as possible and to advance React Native for both WPF and UWP in parallel.

I can't speak as to why there's no mention of RNW at all on Facebook'a React Native documentation.

**Comment by rozele** [comment]
Thanks @alexandrubeu, we've been keeping up with the regular releases of react-native for about 6 months now, and plan to continue this.  I posted to the Core Contributors community to start brainstorming about cross posting of documentation https://www.facebook.com/groups/reactnativeoss/permalink/1617709961858965/

**Comment by danielearwicker** [comment]
@matthargett I've recently had to work on extending a "traditional" WPF application and wished I had React+TypeScript. Are you saying this project targets WPF? Is it something I could use in a modular way within an existing C#/WPF application? I can't see a hint of that in the introductory docs - it's all about Universal Apps.

**Comment by matthargett** [comment]
@danielearwicker WPF support is there in the code, and we ( @GantMan , mainly ) are working on the CLI piece so a react-native-windows project can be created as easily as it is work UWP right now. Once the developer experience is reasonable, we'll update the documentation. Our internally-developed RNW application is only targeting WPF, not UWP, and is working well so far for us :)

As far as using it in a modular way, react-native-windows really wants full control of the application windows at this point in time. I think you could possibly host RNW flows in a child window of your main application, but the only way to find out would be to try it :)

**Comment by matthargett** [comment]
I think the question was answered. Please re-open if there's more specific questions.
