### ISSUE TITLE
Picker component does not visually update correctly.

### ISSUE THREAD

**Issue by josephan** [ReactWindows/react-native-windows#911]
Version:
react-native: ^0.35.0
react-native-windows: ^0.35.0
rnpm-plugin-windows: ^0.2.3

When the `Picker` component is updated by an incoming prop update or an internal state update, new `Picker.Items` are added to the dropdown list instead of replacing the existing items.

Here is a demonstration:
![giphy](https://cloud.githubusercontent.com/assets/8878596/20631201/78929a20-b303-11e6-910b-633bd5aa66e9.gif)

clicking on the newly added items will crash the app.

**Comment by matthargett** [comment]
Hi @josephan ! @rozele or @pre10der89 can comment on the bug itself, but I just wanted to thank you for your fantastic bug reports so far. Capturing the animated GIFs and providing sample repos is super helpful! :)

**Comment by josephan** [comment]
@matthargett You're welcome!

**Comment by rozele** [comment]
@josephan can you confirm if #914 resolves the issue?
