### ISSUE TITLE
WPF: Views Without Specific Styles Aren't Created

### ISSUE THREAD

**Issue by kevinvangelder** [ReactWindows/react-native-windows#919]
Creating a View with children but without specific styles (namely backgroundColor or borderWidth), such as `<View><Text>Test</Text></View>`, does not create a wrapping view (Canvas), according to Visual Studio's Live Visual Tree, however the TextBlock is created.

After some initial debugging I've ruled out the possibility of the C# code being at fault, as the `return new Canvas();` line of the ReactViewManager is not called for the wrapping view unless it has style properties.

I verified that iOS does render a wrapping view even when it has no props, so this is something that will be important to figure out.

**Comment by rozele** [comment]
Why is this an issue?  On Android and Windows we have the concept of layout-only views that have no backing in the native UI tree but still have a backing ReactShadowNode / CSSNode to ensure layout properties are applied correctly.  See NativeViewHierarchyOptimizer.cs for more details on how this works.

**Comment by kevinvangelder** [comment]
That's what someone on the Discord channel suggested. I'll read up on that and then update this issue accordingly.

**Comment by kevinvangelder** [comment]
I stand corrected.
