### ISSUE TITLE
Image.getSize not working with ms-appdata scheme

### ISSUE THREAD

**Issue by thebreiflabb** [ReactWindows/react-native-windows#930]
This issue might be somewhat related to [#925](https://github.com/ReactWindows/react-native-windows/issues/925).

Our app saves images during runtime in [LocalFolder](https://msdn.microsoft.com/en-us/library/windows/apps/windows.storage.applicationdata.localfolder.aspx), which we then reference with the `ms-appdata` scheme ([reference](https://msdn.microsoft.com/en-us/library/windows/apps/jj655406#code-snippet-17)). Which I think is the intended usage through react-native on Windows.

When image caching for network images in [v0.38.0 was introduced](https://github.com/ReactWindows/react-native-windows/blob/7ad9ceb069494fa2b58f275f4ff6ceaea2bb2690/ReactWindows/ReactNative/Modules/Image/ImageLoaderModule.cs#L60), `Image.getSize(url)` stopped working for this `ms-appdata` scheme.

To reproduce the issue, I try to get the size of an already saved image:
```javascript
Image.getSize('ms-appdata:///local/offlineFiles/47EA90CA32A9ABE08DC5FBFAE2CD6D74.jpg', (width, height) => {
	console.log(`Got size: ${width}x${height}`);
}, (e) => {
	console.log(`Getting size failed`);
	console.log(e);
});
```

This throws an exception in [ImageLoaderModule.getSize](https://github.com/ReactWindows/react-native-windows/blob/0.38-stable/ReactWindows/ReactNative/Modules/Image/ImageLoaderModule.cs#L60)
```csharp
var bitmapImage = await ImageCache.Instance.GetFromCacheAsync(new Uri(uriString), true);
```
![imagesize-exception](https://cloud.githubusercontent.com/assets/16031158/21007383/e760ae36-bd3c-11e6-9b4a-74c40f1e2c9f.png)

This could possibly be fixed by handling network images and local images differently as in the [fix](https://github.com/ReactWindows/react-native-windows/commit/31fa88c9a40df97edf56afe577e2296f4819d600) to [#925](https://github.com/ReactWindows/react-native-windows/issues/925)

**Comment by rozele** [comment]
@thebreiflabb does the PR I submitted fix the issue?

**Comment by thebreiflabb** [comment]
@rozele Thank you for looking at this so quickly. I'll check this first thing Monday, as I can't build UWP on my current machine.

**Comment by thebreiflabb** [comment]
@rozele the PR fixes it, thank you.
