### ISSUE TITLE
console.groupCollapsed undefined

### ISSUE THREAD

**Issue by kwancherie** [ReactWindows/react-native-windows#931]
Hi,

I was trying to use the mobx-logger (https://www.npmjs.com/package/mobx-logger) and it fails in my UWP react native app because console.groupCollapsed is undefined.

Thanks

**Comment by rozele** [comment]
@kwancherie does this work with react-native on Android or iOS?  It seems that console.groupCollapsed is not supported on any react-native platform: https://github.com/facebook/react-native/blob/master/packager/react-packager/src/Resolver/polyfills/console.js#L485-L493

**Comment by kwancherie** [comment]
I haven't actually tried as I haven't set up my machine for Android
development. I'll do that and see.

Thanks

**Comment by rozele** [comment]
I'm going to close this.  Perhaps you should file a bug against MobX to make sure it works with react-native.
