### ISSUE TITLE
Touchable* does not accept touches in landscape orientation on phones.

### ISSUE THREAD

**Issue by Pokute** [ReactWindows/react-native-windows#945]
As long as the application orientation is on landscape orientation on a phone, the Touchable* controls do not work. Switching to portrait orientation makes the controls functional again.

**Comment by Pokute** [comment]
I tried with a barebones app with only <TouchableHighlight> and UIExplorer and both fail. Granted they aren't the reactnativewindows origin/master directly, but the diff to origin/master didn't show anything that might be the culprit.

**Comment by matthargett** [comment]
From Discord: "I tried with a barebones <TouchableHighlight> and UIExplorer and both fail. Granted they aren't the reactnativewindows master directly, but the diff to origin/master didn't show anything that might be the culprit."

**Comment by rozele** [comment]
I suspect this is related to the work we did to shift the touchable hit box based on the presence or absense of the status bar, hopefully will get a chance to look at this today.

**Comment by veikkaus5** [comment]
Any news on this?

**Comment by lznt** [comment]
Any news on this?
