### ISSUE TITLE
Support shadow under view

### ISSUE THREAD

**Issue by leonskim** [ReactWindows/react-native-windows#953]
Shadow props(`shadowOffset` for an example) work on iOS, and Android has `elevation` to draw shadow under a view component. Any updates on adding shadow to the view component for Windows? It would be very helpful.

**Comment by rozele** [comment]
This should be possible with APIs from Windows.UI.Composition for UWP, but no work has been started on this yet.

**Comment by matthargett** [comment]
Fixed by #998
