### ISSUE TITLE
Could not find react-native-windows@0.40.*. Latest version of react-native-windows is 0.39.1, try switching to react-native@0.39.*.

### ISSUE THREAD

**Issue by davidpodhola** [ReactWindows/react-native-windows#958]
After following [the guide](https://github.com/ReactWindows/react-native-windows#getting-started) on a freshly installed computer, I get this error message

`Could not find react-native-windows@0.40.*. Latest version of react-native-windows is 0.39.1, try switching to react-native@0.39.*.`

**Comment by Warpenguin** [comment]
You can get past this by using an older version of react-native when creating your project:
`react-native init --version="0.39.1" MyProject`

I would definitely like windows to be updated to 0.40.* or even better, merged into the core react-native project.

**Comment by matthargett** [comment]
We're hoping to do a 0.41-rc package this week or next, sorry for the delays. React Native Windows isn't a copy of the upstream React Native repository with changes on top -- it's a platform plug-in. This structure allows us to do releases outside of the regular React Native cadence to respond to emergency hot fixes, and allows users who are maintaining forks to cherry pick Windows-specific improvements without sifting through the noise of commits in other platforms.

Being on a team building an enterprise desktop product using React Native Windows, this gives us more  operational flexibility than RN on iOS or Android. It does mean RNW maintainers (myself included) need to be better about spinning releases to stay in sync. 0.40 was a particularly challenging upstream release for many people to integrate, and we were trying to wait until some of the dust had settled before integrating.

I hope this helps clear things up! :)

**Comment by davidpodhola** [comment]
Yes, thanks :)
