### ISSUE TITLE
Changing text color by state

### ISSUE THREAD

**Issue by leonskim** [ReactWindows/react-native-windows#964]
I'm trying to change the text color by adding `color` style when it's selected. It works when I change `fontSize` instead of `color` in `selectedText`, but `color` doesn't work and the text disappears.

```
// Code
...
<Text style={[Styles.text, this.state.selected && Styles.selectedText]}>
  Test Text!
</Text>
...

// Style
...
selectedText: {
  color: 'red'
}
...
```

**Comment by kevinvangelder** [comment]
Turned out to be a mis-named color variable at fault.

**Comment by leonskim** [comment]
Yup. Closing the issue.
