### ISSUE TITLE
WebView renderer and Video

### ISSUE THREAD

**Issue by nuthinking** [ReactWindows/react-native-windows#973]
Just a question? Which HTML rendered is used by RN on Windows? Edge or WebKit? Also, is a WebView still the best way to playback videos?

Thanks a lot for any info!

**Comment by rozele** [comment]
The WebView uses the default WebView for UWP, which I assume is Edge.  WebView will work for playing videos, but so will https://github.com/react-native-community/react-native-video.

**Comment by nuthinking** [comment]
Do all these support MediaSource for streaming (with random access)? https://developer.mozilla.org/en-US/docs/Web/API/MediaSource

**Comment by nuthinking** [comment]
Is there basically any format/protocol that is not supported natively in React Native for windows (without WebView)? E.g. some Windows proprietary encrypted format. Thanks!

**Comment by rozele** [comment]
@nuthinking The react-native-video component is built using MediaPlayerElement, which was introduced with Windows 10 Anniversary (10.0.14393).  So, react-native-video should support anything supported by MediaPlayerElement.

**Comment by nuthinking** [comment]
Thanks @rozele for all these info!

**Comment by matthargett** [comment]
@kevinvangelder just for complete info in this issue, what did we end up doing for the video element in our RNW WPF test?

**Comment by kevinvangelder** [comment]
We were using my branch of React Native Video. It wasn't perfect but most of the basics were in place. https://github.com/react-native-community/react-native-video/pull/385
