### ISSUE TITLE
Fix Yoga deprecation warnings

### ISSUE THREAD

**Issue by matthargett** [ReactWindows/react-native-windows#981]
Saw a bunch of these in AppVeyor:
>C:\projects\react-native-windows\ReactWindows\ReactNative\Shared\UIManager\ReactShadowNode.cs(522,13,522,63): warning CS0618: 'YogaNode.SetMargin(YogaEdge, YogaValue)' is obsolete: 'use Margin properties'
5>C:\projects\react-native-windows\ReactWindows\ReactNative\Shared\UIManager\ReactShadowNode.cs(532,20,532,63): warning CS0618: 'YogaNode.GetPadding(YogaEdge)' is obsolete: 'use Padding properties'
5>C:\projects\react-native-windows\ReactWindows\ReactNative\Shared\UIManager\ReactShadowNode.cs(563,20,563,62): warning CS0618: 'YogaNode.GetBorder(YogaEdge)' is obsolete: 'use BorderWidth properties'
5>C:\projects\react-native-windows\ReactWindows\ReactNative\Shared\UIManager\ReactShadowNode.cs(573,13,573,68): warning CS0618: 'YogaNode.SetBorder(YogaEdge, float)' is obsolete: 'use BorderWidth properties'
5>C:\projects\react-native-windows\ReactWindows\ReactNative\Shared\UIManager\ReactShadowNode.cs(583,13,583,67): warning CS0618: 'YogaNode.SetPosition(YogaEdge, YogaValue)' is obsolete: 'use Position properties'
5>C:\projects\react-native-windows\ReactWindows\ReactNative\Shared\UIManager\ReactShadowNode.cs(1019,25,1019,105): warning CS0618: 'YogaNode.SetPadding(YogaEdge, YogaValue)' is obsolete: 'use Padding properties'

**Comment by rozele** [comment]
This was resolved as of #992
